// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbiContract } from "./AbiContract";
import type { AbiStructType } from "./AbiStructType";

/**
 * Top-level ABI shape — the ABI emitted by
 * the PSY compiler. Mirrors `Abi` in
 * `client_prover/psy_core/psy_data/src/abi.rs`.
 */
export type Abi = {
	schema_version: string,
	contract: AbiContract,
	types: Array<AbiStructType>,
};