// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QHashOut } from "./QHashOut";

export type AttestTreeAwareProofInTreeInput = { fingerprint: QHashOut, inner_public_inputs_hash: QHashOut, historical_root_proof: MerkleProofCore<QHashOut>, inclusion_proof: MerkleProofCore<QHashOut>, };
