// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QHashOut } from "./QHashOut";

export type AttestProofInTreeInput = { fingerprint: QHashOut, public_inputs_hash: QHashOut, inclusion_proof: MerkleProofCore<QHashOut>, };
