// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type BasicRealmStatus = { checkpoint_id: bigint, realm_root_hash: QHashOut, };
