// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type ContractMetaData = { checkpoint_id: bigint, contract_id: bigint, deployer: QHashOut, function_whitelist_root: QHashOut, };
