// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbiStateField } from "./AbiStateField";
import type { AbiMethod } from "./AbiMethod";

export type AbiContract = {
	name: string,
	state_tree_height: number,
	state: Array<AbiStateField>,
	methods: Array<AbiMethod>,
};