// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { IMTContractStateUpdate } from "./IMTContractStateUpdate";

export type ContractStateUpdate = { "Positional": { delta_proof: DeltaMerkleProofCore, } } | { "IMT": { update: IMTContractStateUpdate, } };
