// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type DapenCFCUserTransactionEndContext = { end_contract_state_tree_root: QHashOut, end_deferred_tx_debt_tree_root: QHashOut, outputs_hash: QHashOut, outputs_length: bigint, total_events_emitted: bigint, total_balance_spent: bigint, };
