// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PsyCheckpointGlobalStateRoots } from "./PsyCheckpointGlobalStateRoots";
import type { PsyCheckpointLeaf } from "./PsyCheckpointLeaf";
import type { PsyUserLeaf } from "./PsyUserLeaf";
import type { QHashOut } from "./QHashOut";

export type DapenCFCProvingSessionStartContext = { checkpoint_id: bigint, checkpoint_tree_root: QHashOut, checkpoint_leaf: PsyCheckpointLeaf, state_roots: PsyCheckpointGlobalStateRoots, start_session_user_leaf: PsyUserLeaf, };
