// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DPNProvingSessionCompactMethodCall } from "./DPNProvingSessionCompactMethodCall";
import type { QHashOut } from "./QHashOut";

export type DapenCFCUserTransactionCallStartContext = { start_user_contract_tree_root: QHashOut, start_contract_state_tree_root: QHashOut, call_data: DPNProvingSessionCompactMethodCall, start_deferred_tx_debt_tree_root: QHashOut, start_user_balance: bigint, start_user_event_index: bigint, };
