// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DapenCFCUserTransactionInputContext } from "./DapenCFCUserTransactionInputContext";
import type { PsyCmdWithInputAndWitness } from "./PsyCmdWithInputAndWitness";
import type { PsyUserEventRecord } from "./PsyUserEventRecord";
import type { QHashOut } from "./QHashOut";

export type DapenContractFunctionCircuitInput = { inputs: Array<bigint>, outputs: Array<bigint>, events: Array<PsyUserEventRecord>, cmd_witnesses: Array<PsyCmdWithInputAndWitness>, session_proof_tree_root: QHashOut, tx_input_ctx: DapenCFCUserTransactionInputContext, };
