// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MerkleProofCore } from "./MerkleProofCore";
import type { PsyContractLeaf } from "./PsyContractLeaf";
import type { QHashOut } from "./QHashOut";

export type DPNContractLeafWitness = { contract_leaf: PsyContractLeaf, contract_tree_proof: MerkleProofCore<QHashOut>, };
