// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DPNProvingSessionSimpleMethodCall } from "./DPNProvingSessionSimpleMethodCall";
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";

export type DPNInvokeDeferredMethodCallWitness = { call_data: DPNProvingSessionSimpleMethodCall, insertion_proof: DeltaMerkleProofCore, };
