// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Get an IMT contract state value by 256-bit key (self user, external contract).
 */
export type DPNStateCmdGetSelfUserExternalIMTContractStateValue = { contract_id: bigint, base_offset: bigint, capacity: bigint, key: [bigint, bigint, bigint, bigint], contract_state_tree_height: number, };
