// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DPNCheckpointGlobalStateRootsWitness } from "./DPNCheckpointGlobalStateRootsWitness";
import type { DPNCheckpointLeafStatsWitness } from "./DPNCheckpointLeafStatsWitness";
import type { DPNClearEntireTreeWitness } from "./DPNClearEntireTreeWitness";
import type { DPNContractLeafWitness } from "./DPNContractLeafWitness";
import type { DPNIMTContainsWitness } from "./DPNIMTContainsWitness";
import type { DPNIMTOtherUserReadWitness } from "./DPNIMTOtherUserReadWitness";
import type { DPNIMTReadWitness } from "./DPNIMTReadWitness";
import type { DPNIMTSelfUserExternalReadWitness } from "./DPNIMTSelfUserExternalReadWitness";
import type { DPNIMTSetWitness } from "./DPNIMTSetWitness";
import type { DPNInvokeDeferredMethodCallWitness } from "./DPNInvokeDeferredMethodCallWitness";
import type { DPNReadOtherUserContractStateLeafMerkleProof } from "./DPNReadOtherUserContractStateLeafMerkleProof";
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QHashOut } from "./QHashOut";

export type DPNStateCmdWitness = { "MerkleProof": MerkleProofCore<QHashOut> } | { "DeltaMerkleProof": DeltaMerkleProofCore } | { "MerkleProofArray": Array<MerkleProofCore<QHashOut>> } | { "DeltaMerkleProofArray": Array<DeltaMerkleProofCore> } | { "ReadOtherUserContractState": DPNReadOtherUserContractStateLeafMerkleProof } | { "InvokeExternalContractFunctionDeferred": DPNInvokeDeferredMethodCallWitness } | { "CheckpointLeafStats": DPNCheckpointLeafStatsWitness } | { "CheckpointGlobalStateRoots": DPNCheckpointGlobalStateRootsWitness } | { "ClearEntireTree": DPNClearEntireTreeWitness } | { "ContractLeaf": DPNContractLeafWitness } | { "IMTSet": DPNIMTSetWitness } | { "IMTContains": DPNIMTContainsWitness } | { "IMTRead": DPNIMTReadWitness } | { "IMTSelfUserExternalRead": DPNIMTSelfUserExternalReadWitness } | { "IMTOtherUserRead": DPNIMTOtherUserReadWitness } | { "TargetArray": Array<bigint> } | { "TargetArray2D": Array<Array<bigint>> };
