// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Get an IMT contract state value by 256-bit key (self user, current contract).
 */
export type DPNStateCmdGetSelfUserCurrentIMTContractStateValue = { base_offset: bigint, capacity: bigint, key: [bigint, bigint, bigint, bigint], };
