// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { IMTContractStateUpdate } from "./IMTContractStateUpdate";

/**
 * Contract state update history using Indexed Merkle Trees.
 * Replaces the positional `PsyContractStateUpdateHistory` for all contracts.
 */
export type IMTContractStateUpdateHistory = { 
/**
 * Proof that updates the user's contract tree (maps contract_id -> state root)
 */
user_contract_tree_update_proof: DeltaMerkleProofCore, 
/**
 * IMT contract state tree updates (insert or update operations)
 */
imt_updates: Array<IMTContractStateUpdate>, };
