// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { IMTContractStateLeaf } from "./IMTContractStateLeaf";

/**
 * For IMT contracts, each state update is either an insert or an update.
 * This is used in the end cap submission and circuit verification.
 */
export type IMTContractStateUpdate = { "Update": { old_preimage: IMTContractStateLeaf, new_preimage: IMTContractStateLeaf, delta_proof: DeltaMerkleProofCore, } } | { "Insert": { predecessor_old_preimage: IMTContractStateLeaf, predecessor_new_preimage: IMTContractStateLeaf, new_leaf_preimage: IMTContractStateLeaf, predecessor_delta_proof: DeltaMerkleProofCore, new_leaf_delta_proof: DeltaMerkleProofCore, } };
