// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IMTContractStateLeaf } from "./IMTContractStateLeaf";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QHashOut } from "./QHashOut";

/**
 * Membership proof: proves key K exists in the IMT with value V.
 *
 * Verification:
 * 1. Compute leaf_hash = hash(leaf preimage)
 * 2. Verify merkle_proof.value == leaf_hash
 * 3. Verify merkle_proof against the known tree root
 * 4. Confirm leaf.key == target_key
 */
export type IMTMembershipProof = { 
/**
 * The full leaf preimage (key, value, next_key, next_index)
 */
leaf: IMTContractStateLeaf, 
/**
 * Standard merkle proof of the leaf hash
 */
merkle_proof: MerkleProofCore<QHashOut>, };
