// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IMTContractStateLeaf } from "./IMTContractStateLeaf";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QHashOut } from "./QHashOut";

/**
 * Non-membership proof: proves key K does NOT exist in the IMT.
 *
 * Verification:
 * 1. Compute pred_hash = hash(predecessor_leaf preimage)
 * 2. Verify merkle_proof.value == pred_hash
 * 3. Verify merkle_proof against the known tree root
 * 4. Confirm predecessor_leaf.key < target_key
 * 5. Confirm predecessor_leaf.next_key > target_key OR predecessor_leaf.next_key == 0 (end)
 */
export type IMTNonMembershipProof = { 
/**
 * The predecessor leaf: pred.key < target_key < pred.next_key
 */
predecessor_leaf: IMTContractStateLeaf, 
/**
 * Proof of the predecessor's leaf hash in the merkle tree
 */
merkle_proof: MerkleProofCore<QHashOut>, };
