// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IMTContractStateLeaf } from "./IMTContractStateLeaf";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QHashOut } from "./QHashOut";

/**
 * Predecessor result: used by clients to construct insertion transaction deltas.
 *
 * Contains the predecessor leaf, its merkle proof, and the next append index.
 */
export type IMTPredecessorResult = { 
/**
 * Position of the predecessor leaf in the tree
 */
predecessor_leaf_index: bigint, 
/**
 * Full preimage of the predecessor leaf
 */
predecessor_leaf: IMTContractStateLeaf, 
/**
 * Merkle proof of the predecessor leaf hash
 */
predecessor_merkle_proof: MerkleProofCore<QHashOut>, 
/**
 * Where the next leaf will be appended
 */
next_append_index: bigint, };
