// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/** Map kind — `#[serde(rename_all = "snake_case")]`. */
export type MapKind = "contract_hash_map" | "map" | "namespaced_map";