// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbiParam } from "./AbiParam";
import type { StateMutability } from "./StateMutability";

export type AbiMethod = {
	name: string,
	method_id: number,
	state_mutability: StateMutability,
	inputs: Array<AbiParam>,
	outputs: Array<AbiParam>,
	input_felt_count: number,
	output_felt_count: number,
	vm_type?: string,
};