// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/** Primitive type names. Serialized verbatim (no serde rename). */
export type PrimitiveTypeName = "Felt" | "Bool" | "U32" | "Hash";