// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MerkleProofCore } from "./MerkleProofCore";
import type { PsyContractInclusionProof } from "./PsyContractInclusionProof";
import type { QHashOut } from "./QHashOut";

export type PsyContractFunctionInclusionProof = { contract_inclusion_proof: PsyContractInclusionProof, contract_function_merkle_proof: MerkleProofCore<QHashOut>, };
