// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type PsyIMTSlotUpdate = { key: QHashOut, old_value: QHashOut, new_value: QHashOut, is_insert: boolean, };
