// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type RegisterUserMetaData = { checkpoint_id: bigint, registration_id: bigint, user_id: bigint, public_key_param: QHashOut, fingerprint: QHashOut, };
