// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration for a software-defined key circuit.
 *
 * Defines what capabilities the key circuit has and what it can introspect.
 */
export type SDKeyConfig = { 
/**
 * Number of transactions the key circuit can introspect (compile-time constant).
 * Each introspectable transaction adds circuit constraints for the merkle proof
 * of that transaction's position in the tx_stack_hash chain.
 */
num_introspectable_transactions: number, 
/**
 * Whether this key circuit can read contract state at the current checkpoint.
 */
can_read_state: boolean, 
/**
 * Height of the contract state tree if state reading is enabled.
 */
contract_state_tree_height: number, 
/**
 * Whether this key circuit verifies secp256k1 signatures.
 */
requires_secp256k1: boolean, 
/**
 * Number of secp256k1 signature verification slots in the circuit.
 */
num_secp256k1_slots: number, };
