// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SDKeyConfig } from "./SDKeyConfig";

/**
 * Compiled output of an SD key definition.
 *
 * This is the output of compiling a PSY source file as an SD key.
 * It contains the DPN circuit definition for the key authorization logic
 * plus the SD key configuration metadata.
 */
export type SDKeyDefinition = { 
/**
 * The compiled authorization logic as a DPN function circuit.
 */
authorization_circuit: Array<number>, 
/**
 * SD key configuration.
 */
config: SDKeyConfig, 
/**
 * Name of the key definition (from the contract name).
 */
name: string, };
