// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

/**
 * Secp256k1 signature data provided as witness to the SD key circuit.
 */
export type SDKeySecp256k1WitnessSlot = { 
/**
 * The compressed public key (as 16 field elements for circuit representation).
 */
public_key: [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint], 
/**
 * The message hash being signed.
 */
msg_hash: QHashOut, 
/**
 * The signature (as 16 field elements for circuit representation).
 */
signature: [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint], };
