// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SDKKeyConfig } from "./SDKKeyConfig";

/**
 * Compiled output of an SDK key definition.
 *
 * This is the output of compiling a PSY source file as an SDK key.
 * It contains the DPN circuit definition for the key authorization logic
 * plus the SDK key configuration metadata.
 */
export type SDKKeyDefinition = { 
/**
 * The compiled authorization logic as a DPN function circuit.
 */
authorization_circuit: Array<number>, 
/**
 * SDK key configuration.
 */
config: SDKKeyConfig, 
/**
 * Name of the key definition (from the contract name).
 */
name: string, };
