// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

/**
 * Compact transaction info for SDK key introspection.
 *
 * Each transaction in a proving session can be introspected by the SDK key
 * circuit at a compile-time-constant index. This struct holds the information
 * available for each transaction: the contract being called, the method,
 * and a hash of the inputs.
 */
export type SDKKeyTransactionInfo = { 
/**
 * Which contract this transaction calls.
 */
contract_id: bigint, 
/**
 * The method ordinal (method_id) of the contract function being called.
 */
method_id: bigint, 
/**
 * The calling contract id (or default caller for user-initiated txs).
 */
caller_contract_id: bigint, 
/**
 * Number of inputs to the function call.
 */
inputs_length: bigint, 
/**
 * Hash of the inputs.
 */
inputs_hash: QHashOut, };
