// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PsyUserLeaf } from "./PsyUserLeaf";
import type { QHashOut } from "./QHashOut";

export type SignContext = { checkpoint_tree_root: QHashOut, user_leaf: PsyUserLeaf, };
