// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/** Method state mutability — `#[serde(rename_all = "lowercase")]`. */
export type StateMutability = "view" | "external";