// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TypeRef } from "./TypeRef";

export type AbiStateField = {
	name: string,
	type: TypeRef,
	offset: number,
	felt_size: number,
};