// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbiStructField } from "./AbiStructField";
import type { AbiTypeKind } from "./AbiTypeKind";

export type AbiStructType = {
	kind: AbiTypeKind,
	name: string,
	felt_size: number,
	fields: Array<AbiStructField>,
};