// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IMTContractStateUpdateHistory } from "./IMTContractStateUpdateHistory";
import type { PsyUserEventRecord } from "./PsyUserEventRecord";
import type { SubmitUserEndCapNonProofCoreInput } from "./SubmitUserEndCapNonProofCoreInput";

/**
 * IMT-based end cap input. All contracts use IMT unconditionally.
 */
export type SubmitUserEndCapIMTNonProofInput = { core: SubmitUserEndCapNonProofCoreInput, contract_state_updates: Array<IMTContractStateUpdateHistory>, events: Array<PsyUserEventRecord>, };
