// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrimitiveTypeName } from "./PrimitiveTypeName";
import type { MapKind } from "./MapKind";

/**
 * Type reference — an internally-tagged serde enum
 * (`#[serde(tag = "kind", rename_all = "snake_case")]`). The `kind` field is
 * a sibling of the variant's other fields, not a wrapper.
 */
export type TypeRef =
	| { kind: "primitive", name: PrimitiveTypeName }
	| { kind: "struct", name: string }
	| { kind: "array", item: TypeRef, length: number, item_felt_size: number }
	| {
		kind: "map",
		map_kind: MapKind,
		key: TypeRef,
		value: TypeRef,
		capacity: number,
		value_felt_size: number,
		alignment_felts: number,
	};