// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/** Struct type kind — `#[serde(rename_all = "snake_case")]`. Currently only `struct`. */
export type AbiTypeKind = "struct";