// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DapenCFCUserTransactionInputContext } from "./DapenCFCUserTransactionInputContext";
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { IMTContractStateUpdate } from "./IMTContractStateUpdate";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QHashOut } from "./QHashOut";

/**
 * IMT-based CFC state delta input. Parallels `UPSCFCStandardStateDeltaInput`
 * but uses IMT contract state updates instead of positional merkle proofs.
 */
export type UPSCFCStandardIMTStateDeltaInput = { cfc_transaction_input_context: DapenCFCUserTransactionInputContext, user_contract_tree_update_proof: DeltaMerkleProofCore, imt_state_updates: Array<IMTContractStateUpdate>, deferred_tx_debt_pivot_proof: MerkleProofCore<QHashOut>, inline_tx_debt_pivot_proof: MerkleProofCore<QHashOut>, };
