// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DapenCFCUserTransactionInputContext } from "./DapenCFCUserTransactionInputContext";
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QHashOut } from "./QHashOut";

export type UPSCFCStandardStateDeltaInput = { cfc_transaction_input_context: DapenCFCUserTransactionInputContext, user_contract_tree_update_proof: DeltaMerkleProofCore, deferred_tx_debt_pivot_proof: MerkleProofCore<QHashOut>, inline_tx_debt_pivot_proof: MerkleProofCore<QHashOut>, };
