// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UPSVerifyCFCStandardStepInput } from "./UPSVerifyCFCStandardStepInput";
import type { VerifyPreviousUPSStepProofInProofTreeInput } from "./VerifyPreviousUPSStepProofInProofTreeInput";

export type UPSCFCStandardTransactionCircuitInput = { verify_previous_ups_step: VerifyPreviousUPSStepProofInProofTreeInput, standard_cfc_step: UPSVerifyCFCStandardStepInput, };
