// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UPSVerifyPopDeferredTxStepInput } from "./UPSVerifyPopDeferredTxStepInput";
import type { VerifyPreviousUPSStepProofInProofTreeInput } from "./VerifyPreviousUPSStepProofInProofTreeInput";

export type UPSCFCDeferredTransactionCircuitInput = { verify_previous_ups_step: VerifyPreviousUPSStepProofInProofTreeInput, deferred_tx_cfc_step: UPSVerifyPopDeferredTxStepInput, };
