// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttestProofInTreeInput } from "./AttestProofInTreeInput";
import type { QHashOut } from "./QHashOut";
import type { VerifyPreviousUPSStepProofInProofTreeInput } from "./VerifyPreviousUPSStepProofInProofTreeInput";

export type UPSEndCapFromProofTreeGadgetInput = { verify_previous_ups_step_input: VerifyPreviousUPSStepProofInProofTreeInput, verify_zk_signature_proof_input: AttestProofInTreeInput, user_public_key_param: QHashOut, nonce: bigint, slots_modified: bigint, second_to_last_tx_hash_stack: QHashOut, };
