// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MerkleProofCore } from "./MerkleProofCore";
import type { PsyCheckpointGlobalStateRoots } from "./PsyCheckpointGlobalStateRoots";
import type { PsyCheckpointLeaf } from "./PsyCheckpointLeaf";
import type { QHashOut } from "./QHashOut";
import type { UserProvingSessionHeader } from "./UserProvingSessionHeader";

export type UPSStartStepRegisterUserInput = { ups_header: UserProvingSessionHeader, checkpoint_leaf: PsyCheckpointLeaf, state_roots: PsyCheckpointGlobalStateRoots, checkpoint_tree_proof: MerkleProofCore<QHashOut>, user_tree_proof: MerkleProofCore<QHashOut>, user_registration_tree_proof: MerkleProofCore<QHashOut>, };
