// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttestTreeAwareProofInTreeInput } from "./AttestTreeAwareProofInTreeInput";
import type { PsyCheckpointLeafCompactWithStateRoots } from "./PsyCheckpointLeafCompactWithStateRoots";
import type { PsyContractFunctionInclusionProof } from "./PsyContractFunctionInclusionProof";
import type { UPSCFCStandardStateDeltaInput } from "./UPSCFCStandardStateDeltaInput";

export type UPSVerifyCFCStandardStepInput = { checkpoint_state: PsyCheckpointLeafCompactWithStateRoots, verify_cfc_proof_input: AttestTreeAwareProofInTreeInput, cfc_inclusion_proof: PsyContractFunctionInclusionProof, process_cfc_state_delta_input: UPSCFCStandardStateDeltaInput, };
