// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { UPSVerifyCFCStandardStepInput } from "./UPSVerifyCFCStandardStepInput";

export type UPSVerifyPopDeferredTxStepInput = { standard_cfc_verify_input: UPSVerifyCFCStandardStepInput, ups_pop_deferred_tx_proof: DeltaMerkleProofCore, };
