// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";
import type { UserProvingSessionCurrentState } from "./UserProvingSessionCurrentState";
import type { UserProvingSessionStartContext } from "./UserProvingSessionStartContext";

export type UserProvingSessionHeader = { ups_step_circuit_whitelist_root: QHashOut, session_start_context: UserProvingSessionStartContext, current_state: UserProvingSessionCurrentState, };
