// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type UserEndCapMetaData = { checkpoint_id: bigint, realm_id: number, user_id: bigint, start_user_leaf_hash: QHashOut, end_user_leaf_hash: QHashOut, };
