// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PsyUserLeaf } from "./PsyUserLeaf";
import type { QHashOut } from "./QHashOut";

export type UserProvingSessionCurrentState = { user_leaf: PsyUserLeaf, deferred_tx_debt_tree_root: QHashOut, inline_tx_debt_tree_root: QHashOut, tx_hash_stack: QHashOut, tx_count: bigint, };
