// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PsyUserLeaf } from "./PsyUserLeaf";
import type { QHashOut } from "./QHashOut";

export type UserContractState = { checkpoint_tree_root: QHashOut, user_leaf: PsyUserLeaf, start_contract_state_root: QHashOut, contract_id: bigint, checkpoint_id: bigint, };
