// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PsyUserLeaf } from "./PsyUserLeaf";
import type { QHashOut } from "./QHashOut";

export type UserProvingSessionStartContext = { checkpoint_id: bigint, checkpoint_tree_root: QHashOut, checkpoint_leaf_hash: QHashOut, start_session_user_leaf: PsyUserLeaf, };
