// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttestTreeAwareProofInTreeInput } from "./AttestTreeAwareProofInTreeInput";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QHashOut } from "./QHashOut";
import type { UserProvingSessionHeader } from "./UserProvingSessionHeader";

export type VerifyPreviousUPSStepProofInProofTreeInput = { proof_attestation_witness: AttestTreeAwareProofInTreeInput, previous_step_header: UserProvingSessionHeader, ups_circuit_whitelist_merkle_proof: MerkleProofCore<QHashOut>, };
