[package]
name = "sp1-plonky2-script"
version = "0.1.0"
edition = "2021"
default-run = "main"

[[bin]]
name = "main"
path = "src/bin/main.rs"

[[bin]]
name = "evm"
path = "src/bin/evm.rs"

[[bin]]
name = "vkey"
path = "src/bin/vkey.rs"

[[bin]]
name = "matrix"
path = "src/bin/matrix.rs"

[dependencies]
sp1-sdk = { workspace = true }
serde_json = { workspace = true, features = ["alloc"] }
serde = { workspace = true, features = ["derive"] }
clap = { workspace = true }
tracing = { workspace = true }
hex = { workspace = true }
dotenv = { workspace = true }
anyhow = { workspace = true }
sp1-plonky2-lib = { path = "../lib" }

[build-dependencies]
sp1-build = { workspace = true }
