#!/usr/bin/env bash

write_envio_contracts() {
  : "${ENVIO_CONFIG_FILE:=config.yaml}"
  cat >"$ENVIO_CONFIG_FILE" <<'EOF'
# Envio config generated by deploy/gcp/remote/install-envio.sh.
name: psy-relayer-indexer
field_selection:
  transaction_fields:
    - hash

contracts:
  - name: Bridge
    handler: ./handlers.ts
    events:
      - event: WithdrawalClaimed(bytes32 indexed nullifier, address indexed recipient, address indexed token, uint256 amount)
      - event: DepositRecorded(uint32 indexed index, bytes32 shieldAddress, address indexed token, bytes32 l2TokenContractId, uint256 amount, uint8 chainIndex, bytes32 noteCommitment, bytes32 leafHash)
  - name: StateManager
    handler: ./handlers.ts
    events:
      - event: Finalized(uint64 indexed newLastFinalizedCheckpointId, bytes32 indexed newLastVerifiedCheckpointRoot, bytes32 depositTreeRoot, bytes32 withdrawalTreeRoot)

networks:
EOF
}

append_envio_network() {
  local chain_id="$1"
  local start_block="$2"
  local rpc_url="$3"
  local bridge_address="$4"
  local state_manager_address="$5"
  local use_hypersync="$6"
  local hypersync_url="$7"

  : "${ENVIO_CONFIG_FILE:=config.yaml}"
  cat >>"$ENVIO_CONFIG_FILE" <<EOF
  - id: ${chain_id}
    start_block: ${start_block}
    confirmed_block_threshold: ${ENVIO_CONFIRMED_BLOCK_THRESHOLD}
EOF

  if [ "$use_hypersync" = "true" ] || [ "$use_hypersync" = "1" ]; then
    if [ -n "$hypersync_url" ]; then
      cat >>"$ENVIO_CONFIG_FILE" <<EOF
    hypersync_config:
      url: ${hypersync_url}
EOF
    fi
    cat >>"$ENVIO_CONFIG_FILE" <<EOF
    rpc:
      - url: ${rpc_url}
        for: fallback
        initial_block_interval: ${ENVIO_RPC_INITIAL_BLOCK_INTERVAL}
        backoff_multiplicative: ${ENVIO_RPC_BACKOFF_MULTIPLICATIVE}
        acceleration_additive: ${ENVIO_RPC_ACCELERATION_ADDITIVE}
        interval_ceiling: ${ENVIO_RPC_INTERVAL_CEILING}
        backoff_millis: ${ENVIO_RPC_BACKOFF_MILLIS}
        fallback_stall_timeout: ${ENVIO_RPC_FALLBACK_STALL_TIMEOUT_MILLIS}
        query_timeout_millis: ${ENVIO_RPC_QUERY_TIMEOUT_MILLIS}
EOF
  else
    cat >>"$ENVIO_CONFIG_FILE" <<EOF
    rpc_config:
      url: ${rpc_url}
      initial_block_interval: ${ENVIO_RPC_INITIAL_BLOCK_INTERVAL}
      backoff_multiplicative: ${ENVIO_RPC_BACKOFF_MULTIPLICATIVE}
      acceleration_additive: ${ENVIO_RPC_ACCELERATION_ADDITIVE}
      interval_ceiling: ${ENVIO_RPC_INTERVAL_CEILING}
      backoff_millis: ${ENVIO_RPC_BACKOFF_MILLIS}
      fallback_stall_timeout: ${ENVIO_RPC_FALLBACK_STALL_TIMEOUT_MILLIS}
      query_timeout_millis: ${ENVIO_RPC_QUERY_TIMEOUT_MILLIS}
EOF
  fi

  cat >>"$ENVIO_CONFIG_FILE" <<EOF
    contracts:
      - name: Bridge
        address:
          - ${bridge_address}
      - name: StateManager
        address:
          - ${state_manager_address}
EOF
}

write_envio_config() {
  local chain
  write_envio_contracts

  if [ -n "${ENVIO_CHAINS_JSON:-}" ]; then
    jq -e '
      .chains | type == "array" and length >= 2
      and all(.[];
        (.chain_id | type == "number")
        and (.start_block | type == "number")
        and (.rpc_url | type == "string" and length > 0)
        and (.bridge_address | type == "string" and length == 42)
        and (.state_manager_address | type == "string" and length == 42)
      )
    ' <<<"$ENVIO_CHAINS_JSON" >/dev/null || {
      echo "invalid ENVIO_CHAINS_JSON" >&2
      return 1
    }
    while IFS= read -r chain; do
      append_envio_network \
        "$(jq -r '.chain_id' <<<"$chain")" \
        "$(jq -r '.start_block' <<<"$chain")" \
        "$(jq -r '.rpc_url' <<<"$chain")" \
        "$(jq -r '.bridge_address' <<<"$chain")" \
        "$(jq -r '.state_manager_address' <<<"$chain")" \
        "$(jq -r '.use_hypersync // false' <<<"$chain")" \
        "$(jq -r '.hypersync_url // ""' <<<"$chain")"
    done < <(jq -c '.chains | sort_by(.chain_index)[]' <<<"$ENVIO_CHAINS_JSON")
    return
  fi

  [ -n "${ETH_RPC_URL:-}" ] || { echo "ETH_RPC_URL is required" >&2; return 1; }
  [ -n "${BRIDGE_ADDRESS:-}" ] || { echo "BRIDGE_ADDRESS is required" >&2; return 1; }
  [ -n "${STATE_MANAGER_ADDRESS:-}" ] || { echo "STATE_MANAGER_ADDRESS is required" >&2; return 1; }
  append_envio_network \
    "$CHAIN_ID" "$START_BLOCK" "$ETH_RPC_URL" "$BRIDGE_ADDRESS" \
    "$STATE_MANAGER_ADDRESS" "$ENVIO_USE_HYPERSYNC" "$ENVIO_HYPERSYNC_URL"
}
