[package]
edition = "2021"
name    = "parth_core"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["rand", "std", "parth_node", "ptypes_goldilocks_qhashout"]
std = []
ptypes_goldilocks_qhashout = ["goldilocks"]
goldilocks = ["plonky2"]
ptypes_u64_hash256 = []
rand = ["dep:rand"]
parth_node = []
serialize_rkyv = ["dep:rkyv", "plonky2?/serialize_rkyv"]
serialize_speedy = ["dep:speedy", "plonky2?/serialize_rkyv"]
serialize_postcard = ["dep:postcard"]

[dependencies]
anyhow     = { workspace = true }
num-traits = { workspace = true }
async-trait      = { workspace = true }
serde      = { workspace = true }
serde_json      = { workspace = true }
serde_repr      = { workspace = true }
serde_with      = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
bincode = { workspace = true }
rand = { workspace = true, optional = true }
auto_impl = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
postcard = { workspace = true, optional = true }
rkyv = { workspace = true, optional = true }
speedy = { workspace = true, optional = true }
ts-rs = { workspace = true }

# start local packages
pser = { workspace = true }
pderive = { workspace = true }

plonky2 = { workspace = true, optional = true }

[dev-dependencies]
plonky2 = { workspace = true }
ts-rs = { workspace = true }
criterion = { workspace = true }



[[bench]]
name = "nca_group_gen"
harness = false
