[package]
edition = "2021"
name    = "psy_plonky2_circuits"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["std", "parth_core/serialize_rkyv", "parth_core/serialize_speedy", "parth_core/serialize_postcard", "serialize_speedy", "gnark-wrap"]
std = ["parth_core/std", "pser/std", "psy_data/std"]
serialize_rkyv = ["dep:rkyv","pser/serialize_rkyv", "parth_core/serialize_rkyv", "psy_data/serialize_rkyv"]
serialize_speedy = ["dep:speedy", "pser/serialize_speedy", "parth_core/serialize_speedy", "psy_data/serialize_speedy"]
serialize_postcard = ["dep:postcard", "pser/serialize_postcard", "parth_core/serialize_postcard", "psy_data/serialize_postcard"]
gnark-wrap = ["dep:gnark-plonky2-wrapper", "dep:gnark-plonky2-verifier-ffi"]

[dependencies]
postcard = { workspace = true, optional = true }
rkyv = { workspace = true, optional = true }
speedy = { workspace = true, optional = true }
anyhow     = { workspace = true }
async-trait      = { workspace = true }
serde      = { workspace = true }
serde_json      = { workspace = true }
serde_repr      = { workspace = true }
serde_with      = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
bincode = { workspace = true }
tracing = { workspace = true }
web-time = { workspace = true }
tokio = { workspace = true}
rand = { workspace = true }
auto_impl = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
hashbrown = { workspace = true }
plonky2 = { workspace = true }
gnark-plonky2-wrapper = { workspace = true, optional = true }
gnark-plonky2-verifier-ffi = { workspace = true, optional = true }
tiny-keccak = { workspace = true }

# start local packages
cf_utils = { workspace = true }
parth_core = { workspace = true }
psy_plonky2_basic_helpers = { workspace = true }
psy_plonky2_common_circuits = { workspace = true }
parth_common = { workspace = true }
psy_core = { workspace = true }
psy_data = { workspace = true }
psy_serialize = { workspace = true }
pser = { workspace = true }
psy_common_circuit = { workspace = true }
psy_crypto = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
jsonrpsee = { workspace = true }
home = { workspace = true }
plonky2x = { git = "https://github.com/logere/succinctx", rev = "eec027a324be98827b4b91b4054f4cac7044ced4" }
psy_dummy_prover = { workspace = true }
psy_worker_core = { workspace = true }
zstd = { workspace = true }


[dev-dependencies]
psy_node_core = { workspace = true }
psy_node_store_memory = { workspace = true }
psy_client_common = { workspace = true }
psy_cli_common = { path = "../psy_cli/psy_cli_common" }
