[package]
edition = "2021"
name    = "parth_common"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow     = { workspace = true }
async-trait      = { workspace = true }
serde      = { workspace = true }
serde_json      = { workspace = true }
serde_repr      = { workspace = true }
serde_with      = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
bincode = { workspace = true }
tracing = { workspace = true }
auto_impl = { workspace = true }
k256 = { workspace = true }
hashbrown = { workspace = true }
postcard = { workspace = true }
rkyv = { workspace = true }
pser = { workspace = true }
speedy = { workspace = true }
ts-rs = { workspace = true }

# start local packages
parth_core = { workspace = true }

[dev-dependencies]
parth_crypto = { workspace = true }
