#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARTH_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONFIG_FILE="${GCP_DEPLOY_CONFIG:-$PARTH_DIR/deploy/gcp/config.env}"
OUT_DIR="${LOCAL_COORDINATOR_WORKERS_DIR:-$PARTH_DIR/dist/local-coordinator-workers}"

[ -f "$CONFIG_FILE" ] || {
  echo "missing config file: $CONFIG_FILE" >&2
  exit 1
}

set -a
# shellcheck source=../gcp/config.env
source "$CONFIG_FILE"
set +a

# shellcheck source=../gcp/lib/common.sh
source "$PARTH_DIR/deploy/gcp/lib/common.sh"

worker_bin="$PARTH_DIR/target/release/psy_worker_cli"
[ -x "$worker_bin" ] || {
  echo "missing worker binary: $worker_bin" >&2
  echo "build it first: cargo build --release --bin psy_worker_cli" >&2
  exit 1
}

run_service="$PARTH_DIR/deploy/bin/run-parth-service"
[ -f "$run_service" ] || {
  echo "missing service runner: $run_service" >&2
  exit 1
}

genesis_path="$PARTH_DIR/genesis.json"
[ -f "$genesis_path" ] || {
  echo "missing genesis file: $genesis_path" >&2
  exit 1
}

private_key="${COORDINATOR_WORKER_PRIVATE_KEY:-}"
worker_key_index="${COORDINATOR_WORKER_KEY_INDEX:-$(select_cyclic_space_list_item "${COORDINATOR_WORKER_KEY_INDEXES:-0 1}" 0)}"
if [ -z "$private_key" ]; then
  private_keys_path="$PARTH_DIR/private_keys.json"
  [ -f "$private_keys_path" ] || {
    echo "missing private_keys.json; set COORDINATOR_WORKER_PRIVATE_KEY or generate genesis first" >&2
    exit 1
  }
  private_key="$(jq -r --argjson idx "$worker_key_index" '.[$idx] // empty' "$private_keys_path")"
fi
[ -n "$private_key" ] || {
  echo "empty coordinator worker private key" >&2
  exit 1
}

mkdir -p "$OUT_DIR/target/release" "$OUT_DIR/deploy/bin" "$OUT_DIR/checkpoints" "$OUT_DIR/logs"
cp "$worker_bin" "$OUT_DIR/target/release/psy_worker_cli"
cp "$run_service" "$OUT_DIR/deploy/bin/run-parth-service"
cp "$genesis_path" "$OUT_DIR/genesis.json"
chmod 0755 "$OUT_DIR/deploy/bin/run-parth-service"

cat > "$OUT_DIR/env" <<EOF
PARTH_HOME=$OUT_DIR
NETWORK=${PARTH_NETWORK:-local-devnet}
PROVING_BACKEND=${PROVING_BACKEND:-plonky2-poseidon-goldilocks}
SCYLLA_DB_URL=127.0.0.1:${LOCAL_SCYLLA_PORT:-19042}
NATS_JETSTREAM_URL=nats://127.0.0.1:${LOCAL_NATS_PORT:-14222}
REDIS_URL=redis://127.0.0.1:${LOCAL_REDIS_PORT:-16379}
GENESIS_DATA_PATH=$OUT_DIR/genesis.json
CHECKPOINT_BACKUP_PATH=$OUT_DIR/checkpoints
WORKER_USER_ID=${COORDINATOR_WORKER_USER_ID:-$(genesis_user_id_for_key_index "$worker_key_index")}
PRIVATE_KEY=$private_key
COORDINATOR_API_URLS=${LOCAL_COORDINATOR_API_URLS:-https://${PUBLIC_COORDINATOR_DOMAIN}}
REALM_API_URLS=
URL_ROTATION_STRATEGY=${URL_ROTATION_STRATEGY:-random}
BATCH_SIZE=${LOCAL_COORDINATOR_WORKER_BATCH_SIZE:-${COORDINATOR_WORKER_BATCH_SIZE:-4}}
NATS_EPHEMERAL_ACK_WAIT_MS=${NATS_EPHEMERAL_ACK_WAIT_MS:-5000}
NATS_WORKER_ACK_WAIT_MS=${NATS_WORKER_ACK_WAIT_MS:-30000}
RUST_LOG=${RUST_LOG:-info}
VERBOSE=${VERBOSE:-1}
EOF
chmod 0600 "$OUT_DIR/env"

cat > "$OUT_DIR/run-worker.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

index="${1:?worker index is required}"
runtime_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

set -a
# shellcheck source=env
source "$runtime_dir/env"
set +a

export COMPLETED_JOBS_LOG_FILE="$runtime_dir/checkpoints/coordinator_worker_${index}.backup"

exec "$runtime_dir/deploy/bin/run-parth-service" worker
EOF
chmod 0755 "$OUT_DIR/run-worker.sh"

cat > "$OUT_DIR/README.md" <<EOF
# Local Coordinator Workers

Generated by \`deploy/local-coordinator-workers/prepare-local-coordinator-workers.sh\`.

Start manually:

\`\`\`bash
cd "$OUT_DIR"
./run-worker.sh 0
./run-worker.sh 1
\`\`\`

The worker services require local SSH tunnels for:

- Scylla: 127.0.0.1:${LOCAL_SCYLLA_PORT:-19042} -> ${SCYLLA_HOST:-10.148.0.23}:9042
- NATS:   127.0.0.1:${LOCAL_NATS_PORT:-14222} -> ${NATS_HOST:-10.148.0.20}:4222
- Redis:  127.0.0.1:${LOCAL_REDIS_PORT:-16379} -> ${REDIS_HOST:-10.148.0.12}:6379

Install systemd user services:

\`\`\`bash
bash "$PARTH_DIR/deploy/local-coordinator-workers/install-systemd-user-services.sh"
systemctl --user start parth-local-coordinator-worker@0.service
systemctl --user start parth-local-coordinator-worker@1.service
journalctl --user -u 'parth-local-coordinator-worker@*.service' -f
\`\`\`
EOF

echo "prepared local coordinator worker runtime: $OUT_DIR"
echo
echo "next:"
echo "  bash $PARTH_DIR/deploy/local-coordinator-workers/install-systemd-user-services.sh"
