// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type CheckpointStateHashTransition = { old_checkpoint_tree_root: QHashOut, new_checkpoint_tree_root: QHashOut, old_checkpoint_leaf_hash: QHashOut, new_checkpoint_leaf_hash: QHashOut, };
