// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckpointStateHashTransition } from "./CheckpointStateHashTransition";
import type { QHashOut } from "./QHashOut";

export type CheckpointStateTransitionPublicInputs = { checkpoint_transition: CheckpointStateHashTransition, genesis_checkpoint_state_transition_hash: QHashOut, checkpoint_state_transition_circuit_fingerprint: QHashOut, };
