// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContractCodeDefinition } from "./ContractCodeDefinition";

export type ContractCodeDefinitionWithContractId = { contract_id: bigint, code_definition: ContractCodeDefinition, };
