// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalUserTreeAggregatorHeaderWithTagValue } from "./GlobalUserTreeAggregatorHeaderWithTagValue";

export type GlobalUserTreeAggregatorHeaderWithTagValueAndSerializedJobID = { header: GlobalUserTreeAggregatorHeaderWithTagValue, serialized_job_id: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
