// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalUserTreeAggregatorHeader } from "./GlobalUserTreeAggregatorHeader";
import type { QHashOut } from "./QHashOut";

export type GlobalUserTreeAggregatorHeaderWithTagValue = { header_with_stats: GlobalUserTreeAggregatorHeader, new_tag_tree_node_value: QHashOut, };
