// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalUserTreeAggregatorHeader } from "./GlobalUserTreeAggregatorHeader";
import type { QProvingJobDataID } from "./QProvingJobDataID";

export type GlobalUserTreeAggregatorHeaderWithJobId = { header: GlobalUserTreeAggregatorHeader, job_id: QProvingJobDataID, };
