// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalUserTreeAggregatorHeader } from "./GlobalUserTreeAggregatorHeader";
import type { QHashOut } from "./QHashOut";
import type { TagTreeNodePreimage } from "./TagTreeNodePreimage";

export type GlobalUserTreeAggregatorHeaderWithTagPreimage = { header: GlobalUserTreeAggregatorHeader, new_tag_tree_node_preimage: TagTreeNodePreimage<QHashOut>, };
