// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalUserTreeAggregatorHeaderWithTagValue } from "./GlobalUserTreeAggregatorHeaderWithTagValue";

export type GlobalUserTreeAggregatorHeaderWithTagValueAndJobType = { header: GlobalUserTreeAggregatorHeaderWithTagValue, job_type_u32: number, };
