// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalUserTreeAggregatorHeader } from "./GlobalUserTreeAggregatorHeader";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QHashOut } from "./QHashOut";

export type GUTAVerifyTwoGUTALinearUpgradeCheckpointCircuitInput = { left_header: GlobalUserTreeAggregatorHeader, right_header: GlobalUserTreeAggregatorHeader, left_historical_checkpoint_proof: MerkleProofCore<QHashOut>, right_historical_checkpoint_proof: MerkleProofCore<QHashOut>, };
