// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { QHashOut } from "./QHashOut";
import type { VerifyEndCapSimpleStandardInput } from "./VerifyEndCapSimpleStandardInput";

export type GUTAVerifyTwoEndCapCircuitInputV2 = { left_end_cap: VerifyEndCapSimpleStandardInput, left_global_user_tree_delta_merkle_proof: DeltaMerkleProofCore<QHashOut>, right_end_cap: VerifyEndCapSimpleStandardInput, right_global_user_tree_delta_merkle_proof: DeltaMerkleProofCore<QHashOut>, };
