// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { GlobalUserTreeAggregatorHeader } from "./GlobalUserTreeAggregatorHeader";
import type { QHashOut } from "./QHashOut";
import type { VerifyEndCapSimpleStandardInput } from "./VerifyEndCapSimpleStandardInput";

export type GUTAVerifyLeftGUTARightEndCapCircuitInputV2 = { left_header: GlobalUserTreeAggregatorHeader, right_end_cap: VerifyEndCapSimpleStandardInput, right_global_user_tree_delta_merkle_proof: DeltaMerkleProofCore<QHashOut>, };
