// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { GlobalUserTreeAggregatorHeader } from "./GlobalUserTreeAggregatorHeader";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QHashOut } from "./QHashOut";
import type { VerifyEndCapSimpleStandardInput } from "./VerifyEndCapSimpleStandardInput";

export type GUTAVerifyRightGUTALeftEndCapCircuitInputV2 = { left_end_cap: VerifyEndCapSimpleStandardInput, left_global_user_tree_delta_merkle_proof: DeltaMerkleProofCore<QHashOut>, left_historical_checkpoint_merkle_proof: MerkleProofCore<QHashOut>, right_header: GlobalUserTreeAggregatorHeader, };
