// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { GlobalUserTreeAggregatorHeader } from "./GlobalUserTreeAggregatorHeader";
import type { QHashOut } from "./QHashOut";

export type GUTAVerifyTwoGUTACircuitInputV2 = { left_header: GlobalUserTreeAggregatorHeader, left_global_user_tree_delta_merkle_proof: DeltaMerkleProofCore<QHashOut>, right_header: GlobalUserTreeAggregatorHeader, right_global_user_tree_delta_merkle_proof: DeltaMerkleProofCore<QHashOut>, };
