// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { GlobalUserTreeAggregatorHeader } from "./GlobalUserTreeAggregatorHeader";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QHashOut } from "./QHashOut";

export type GUTAVerifyLeftLinearRightLeafUpgradeCheckpointCircuitInput = { left_header: GlobalUserTreeAggregatorHeader, right_header: GlobalUserTreeAggregatorHeader, right_global_user_tree_delta_merkle_proof: DeltaMerkleProofCore<QHashOut>, right_historical_checkpoint_proof: MerkleProofCore<QHashOut>, };
