// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

/**
 * Leaf preimage for an Indexed Merkle Tree leaf in a contract state tree.
 *
 * Each leaf in an IMT stores:
 * - `key`: the 256-bit storage key (e.g., nullifier hash)
 * - `value`: the 256-bit storage value
 * - `next_key`: the key of the successor leaf in sorted order (zero = no successor)
 * - `next_index`: the leaf index of the successor (zero = no successor)
 *
 * The leaf hash is computed from all 13 field elements via the field hasher.
 * Index 0 is always the sentinel leaf with all fields set to zero.
 */
export type IMTContractStateLeaf = { key: QHashOut, value: QHashOut, next_key: QHashOut, next_index: bigint, };
