// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IMTContractStateLeaf } from "./IMTContractStateLeaf";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QHashOut } from "./QHashOut";

/**
 * Membership proof: proves key K exists in the IMT with value V.
 *
 * Contains the leaf preimage (key, value, next_key, next_index) and a standard
 * merkle proof that the leaf's hash is included in the tree at the given index.
 */
export type IMTMembershipProof = { leaf: IMTContractStateLeaf, merkle_proof: MerkleProofCore<QHashOut>, };
