// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IMTContractStateLeaf } from "./IMTContractStateLeaf";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QHashOut } from "./QHashOut";

/**
 * Non-membership proof: proves key K does NOT exist in the IMT.
 *
 * Contains the predecessor leaf (where predecessor.key < K < predecessor.next_key)
 * and a merkle proof that the predecessor leaf hash is included in the tree.
 */
export type IMTNonMembershipProof = { predecessor_leaf: IMTContractStateLeaf, merkle_proof: MerkleProofCore<QHashOut>, };
