// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IMTContractStateLeaf } from "./IMTContractStateLeaf";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QHashOut } from "./QHashOut";

/**
 * Result of a predecessor lookup for a given key.
 *
 * Used by clients constructing transaction deltas: they need to know the
 * predecessor leaf to properly update the linked list pointers.
 */
export type IMTPredecessorResult = { predecessor_leaf_index: bigint, predecessor_leaf: IMTContractStateLeaf, predecessor_merkle_proof: MerkleProofCore<QHashOut>, next_append_index: bigint, };
