// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MerkleLeafNode } from "./MerkleLeafNode";

export type MerkleNodeNest = { parent_index: bigint, children: Array<MerkleLeafNode>, };
