// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MerkleNodeNest } from "./MerkleNodeNest";
import type { ZKPublicKeyInfo } from "./ZKPublicKeyInfo";

export type PsyCompactUserDefinition = { public_key_info: ZKPublicKeyInfo, balance: bigint, nonce: bigint, last_checkpoint_id: bigint, event_index: bigint, constract_state_tree_records: Array<MerkleNodeNest>, };
