// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QEDCheckpointLeaf } from "./QEDCheckpointLeaf";
import type { QEDL2BlockState } from "./QEDL2BlockState";
import type { QHashOut } from "./QHashOut";

export type PsyCoordinatorPendingCheckpointBase = { block_state: QEDL2BlockState, checkpoint_leaf: QEDCheckpointLeaf, checkpoint_leaf_hash: QHashOut, checkpoint_tree_root: QHashOut, };
