// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PsyChainNetworkType = "LocalDevnet" | "PsyTeamDevnet" | "InternalDevnet" | "InternalTestnet" | "InternalPreProduction" | "PsyPublicCanary" | "PsyPublicTestnet" | "PsyMainnet";
