// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type PsyCheckpointStateTransitionGenesisCircuitInput = { checkpoint_tree_root: QHashOut, checkpoint_leaf_hash: QHashOut, genesis_fingerprint: QHashOut, };
