// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PsySlotUpdate } from "./PsySlotUpdate";

export type PsyContractSlotUpdates = { contract_id: number, slot_updates: Array<PsySlotUpdate>, };
