// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PsyCompactUserDefinition } from "./PsyCompactUserDefinition";
import type { QBCDeployContract } from "./QBCDeployContract";
import type { QEDCheckpointLeafStats } from "./QEDCheckpointLeafStats";
import type { QHashOut } from "./QHashOut";

export type PsyGenesisBlockSetupData = { contracts: Array<QBCDeployContract>, users: Array<PsyCompactUserDefinition>, checkpoint_stats: QEDCheckpointLeafStats, deposit_tree_root: QHashOut, withdrawal_tree_root: QHashOut, };
