// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PsyChainNetworkType } from "./PsyChainNetworkType";
import type { QNetworkTreeCircuitSpecificConstantsData } from "./QNetworkTreeCircuitSpecificConstantsData";
import type { QNetworkTreeConstantsData } from "./QNetworkTreeConstantsData";

export type PsyNetworkChainConfig = { network_type: PsyChainNetworkType, tree_constants: QNetworkTreeConstantsData, circuit_constants: QNetworkTreeCircuitSpecificConstantsData, };
