// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type PsyNodeCircuitFingerprintConfig = { guta_circuit_whitelist_root: QHashOut, register_users_circuit_whitelist_root: QHashOut, deploy_contracts_circuit_whitelist_root: QHashOut, checkpoint_state_transition_circuit_fingerprint: QHashOut, genesis_checkpoint_state_transition_fingerprint: QHashOut, };
