// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContractCodeDefinitionWithContractId } from "./ContractCodeDefinitionWithContractId";
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { PsyCoordinatorPendingCheckpointBase } from "./PsyCoordinatorPendingCheckpointBase";
import type { QHashOut } from "./QHashOut";

export type PsyPreparedCoordinatorBlockStateUpdates = { coordinator_id: bigint, checkpoint_id: bigint, unique_pending_id: bigint, proc_checkpoint_unique_id: bigint, old_base: PsyCoordinatorPendingCheckpointBase, new_base: PsyCoordinatorPendingCheckpointBase, update_global_contract_tree_nodes_ffs: Array<number>, update_contract_function_tree_nodes_ffs: Array<number>, new_contract_leaves_ffs: Array<number>, new_contract_code_definitions: Array<ContractCodeDefinitionWithContractId>, update_user_registration_tree_nodes_ffs: Array<number>, new_user_public_keys_ffs: Array<number>, new_public_key_hash_to_user_id_rows_ffs: Array<number>, update_global_user_tree_nodes_ffs: Array<number>, new_realm_guta_reward_tree_node_keys_ffs: Array<number>, checkpoint_tree_update_proof: DeltaMerkleProofCore<QHashOut>, };
