// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";
import type { QProvingJobDataID } from "./QProvingJobDataID";

export type PsyProvingJobMetadata = { expected_public_inputs_hash: QHashOut, reward_tree_node_index: bigint, reward_tree_node_level: number, reward_tree_hash_mode: number, reward_tree_node_children: number, dependencies: Array<QProvingJobDataID>, };
