// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PsyProvingJobMetadata } from "./PsyProvingJobMetadata";
import type { QProvingJobDataID } from "./QProvingJobDataID";

export type PsyProvingJobMetadataWithJobId = { job_id: QProvingJobDataID, metadata: PsyProvingJobMetadata, };
