// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type PsyPreparedRealmBlockStateUpdates = { realm_id: bigint, realm_sub_id: bigint, unique_pending_id: bigint, proc_checkpoint_unique_id: bigint, old_realm_root: QHashOut, new_realm_root: QHashOut, update_global_user_tree_nodes_ffs: Array<number>, update_user_contract_tree_nodes_ffs: Array<number>, update_contract_state_tree_nodes_ffs: Array<number>, update_user_leaves_ffs: Array<number>, update_contract_state_imt_leaves_ffs: Array<number>, };
