// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PsyPreparedRealmBlockStateUpdates } from "./PsyPreparedRealmBlockStateUpdates";
import type { PsyRealmCoordinatorUpdate } from "./PsyRealmCoordinatorUpdate";

export type PsyPreparedRealmBlockStateUpdatesWithCoordinatorUpdate = { prepared_updates: PsyPreparedRealmBlockStateUpdates, coordinator_update: PsyRealmCoordinatorUpdate, };
