// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";
import type { QProvingJobDataID } from "./QProvingJobDataID";
import type { SimpleMerkleNodeKey } from "./SimpleMerkleNodeKey";

export type PsyProvingJobClaimMetadata = { job_id: QProvingJobDataID, reward_tree_tag: QHashOut, reward_tree_tag_preimage: QHashOut, proving_duration_ms: bigint, job_submitted_at: bigint, unique_pending_id: bigint, realm_id: bigint, realm_sub_id: bigint, reward_tree_node_key: SimpleMerkleNodeKey, reward_tree_hash_mode: number, reward_tree_node_children: number, node_type: number, api_url_hash: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
