// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";
import type { QProvingJobDataID } from "./QProvingJobDataID";
import type { TagTreeMerkleProof } from "./TagTreeMerkleProof";

export type PsyProoffMinerRewardProof = { job_id: QProvingJobDataID, tag_tree_proof: TagTreeMerkleProof<QHashOut>, };
