// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GUTAStats } from "./GUTAStats";
import type { PsyUserEventRecord } from "./PsyUserEventRecord";
import type { QEDUserLeaf } from "./QEDUserLeaf";
import type { QHashOut } from "./QHashOut";
import type { QProvingJobDataID } from "./QProvingJobDataID";

export type PsyRealmUserUpdateQueueItem = { job_id: QProvingJobDataID, expected_fake_checkpoint_id: bigint, old_user_leaf_hash: QHashOut, new_user_leaf_hash: QHashOut, new_user_leaf: QEDUserLeaf, stats: GUTAStats, events: Array<PsyUserEventRecord>, };
