// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QEDCheckpointSyncInfoCompact } from "./QEDCheckpointSyncInfoCompact";
import type { QHashOut } from "./QHashOut";
import type { TagTreeMerkleProof } from "./TagTreeMerkleProof";

export type PsyRealmCoordinatorUpdate = { canonical_chain_ref: { network_id: number, chain_epoch: bigint, checkpoint: { checkpoint_id: bigint, checkpoint_hash: QHashOut } }, checkpoint_sync_info: QEDCheckpointSyncInfoCompact, merkle_proof_to_realm_root: MerkleProofCore<QHashOut>, reward_tree_top_proof: TagTreeMerkleProof<QHashOut>, };
