// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckpointStateTransitionPublicInputs } from "./CheckpointStateTransitionPublicInputs";
import type { QEDCheckpointLeaf } from "./QEDCheckpointLeaf";

export type PsyVerifiableCheckpointTransition = { state_transition: CheckpointStateTransitionPublicInputs, checkpoint_leaf: QEDCheckpointLeaf, };
