// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PsyVerifiableCheckpointTransition } from "./PsyVerifiableCheckpointTransition";

export type PsyVerifiableCheckpointTransitionWithProof = { info: PsyVerifiableCheckpointTransition, circuit_type: number, zk_proof: Array<number>, };
