// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PsyProvingJobMetadataWithJobId } from "./PsyProvingJobMetadataWithJobId";
import type { QHashOut } from "./QHashOut";

export type PsyWorkerGetProvingWorkAPIResponse = { job: PsyProvingJobMetadataWithJobId, child_proof_tag_values: Array<QHashOut>, realm_id: bigint, realm_sub_id: bigint, unique_pending_id: bigint, node_type: number, witness: Array<number>, };
