// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PsyWorkerGetProvingWorkAPIResponse } from "./PsyWorkerGetProvingWorkAPIResponse";

export type PsyWorkerGetProvingWorkWithChildProofsAPIResponse = { base: PsyWorkerGetProvingWorkAPIResponse, input_proofs: Array<Array<number>>, };
