// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PsyProvingJobMetadataWithJobId } from "./PsyProvingJobMetadataWithJobId";
import type { QHashOut } from "./QHashOut";
import type { WorkContextToken } from "./WorkContextToken";

export type PsyWorkerGetProvingWorkAPIResponse = { job: PsyProvingJobMetadataWithJobId, child_proof_tag_values: Array<QHashOut>, realm_id: bigint, realm_sub_id: bigint,
/**
 * Opaque canonical WorkContext returned by Edge and echoed unchanged on
 * proof submission. It binds branch, authority, pending/proc and job.
 */
work_context: WorkContextToken, node_type: number, witness: Array<number>, };
