// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QEDCheckpointGlobalStateRoots } from "./QEDCheckpointGlobalStateRoots";
import type { QEDCheckpointLeaf } from "./QEDCheckpointLeaf";
import type { QEDL2BlockState } from "./QEDL2BlockState";
import type { QHashOut } from "./QHashOut";

export type QEDCheckpointSyncInfoCompact = { checkpoint_id: bigint, coordinator_id: bigint, coordinator_sub_id: bigint, coordinator_unique_pending_id: bigint, block_state: QEDL2BlockState, state_roots: QEDCheckpointGlobalStateRoots, checkpoint_leaf: QEDCheckpointLeaf, checkpoint_leaf_hash: QHashOut, checkpoint_tree_root: QHashOut, };
