// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QEDCheckpointGlobalStateRoots } from "./QEDCheckpointGlobalStateRoots";
import type { QEDCheckpointLeafStats } from "./QEDCheckpointLeafStats";

export type QEDCheckpointLeaf = { global_state_roots: QEDCheckpointGlobalStateRoots, stats: QEDCheckpointLeafStats, };
