// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { QEDCheckpointCoreSyncInfo } from "./QEDCheckpointCoreSyncInfo";
import type { QHashOut } from "./QHashOut";

export type QEDCheckpointSyncInfo = { core: QEDCheckpointCoreSyncInfo, checkpoint_tree_update_proof: DeltaMerkleProofCore<QHashOut>, unique_pending_id: bigint, };
