// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { QHashOut } from "./QHashOut";

export type QEDContractStateUpdateHistory = { user_contract_tree_update_proof: DeltaMerkleProofCore<QHashOut>, contract_state_tree_updates: Array<DeltaMerkleProofCore<QHashOut>>, };
