// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QNetworkTreeConstantsData = { checkpoint_tree_height: number, global_user_tree_height: number, global_contract_tree_height: number, contract_function_tree_height: number, coordinator_global_user_tree_height: number, realm_global_user_tree_height: number, max_contract_state_tree_height: number, group_realm_height: number, max_users: bigint, max_realms: number, max_users_per_realm: number, };
