// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PsyUserEventRecord } from "./PsyUserEventRecord";
import type { SubmitUserEndCapNonProofCoreInput } from "./SubmitUserEndCapNonProofCoreInput";

export type SubmitUserEndCapNonProofInput = { core: SubmitUserEndCapNonProofCoreInput, events: Array<PsyUserEventRecord>, };
