// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalUserTreeAggregatorHeaderWithTagValue } from "./GlobalUserTreeAggregatorHeaderWithTagValue";
import type { ProvingJobCircuitType } from "./ProvingJobCircuitType";

export type SubmitGUTARealmResultAPINoProofInput = { guta_header: GlobalUserTreeAggregatorHeaderWithTagValue, circuit_type: ProvingJobCircuitType, };
