// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { QHashOut } from "./QHashOut";
import type { VerifyEndCapSimpleStandardInput } from "./VerifyEndCapSimpleStandardInput";

export type VerifySingleEndCapInputV2 = { guta_circuit_whitelist: QHashOut, core: VerifyEndCapSimpleStandardInput, global_user_tree_sub_root_transition: DeltaMerkleProofCore<QHashOut>, user_id: bigint, };
