// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GUTAStats } from "./GUTAStats";
import type { PartialUpdateNearestCommonAncestorProof } from "./PartialUpdateNearestCommonAncestorProof";
import type { QHashOut } from "./QHashOut";
import type { VerifyEndCapSimpleStandardInput } from "./VerifyEndCapSimpleStandardInput";

export type VerifyLeftGUTARightEndCapInputSimple = { checkpoint_tree_root: QHashOut, stats_a: GUTAStats, b_end_cap: VerifyEndCapSimpleStandardInput, nca_proof: PartialUpdateNearestCommonAncestorProof, total_aggregation_proofs_generated_a: bigint, };
