// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Opaque, canonical wire token for one [`WorkContext`].
 *
 * Workers must echo this token unchanged when submitting a proof. Only the
 * node Edge decodes it and compares every field with the atomically published
 * current [`PendingContext`]. Keeping the fixed-size canonical bytes in the
 * wire type also prevents JSON/RPC clients from constructing a partial
 * context or silently defaulting a newly added field.
 */
export type WorkContextToken = { bytes: Array<number>, };
