/*
some background for your information:

For absolute clarity:
This is a blockchain system which distributes a user state tree across multiple nodes, called realms.
There is a global user state tree where each user's state is stored in a leaf node. The global user state tree is stored as a merkle tree of height H. To improve scalability, the global user state tree is sharded across multiple realms. Each realm is responsible for a subtree of the global user state tree, specifically a subtree of height R, where R < H.

When users perform operations that modify their state (like deposits, withdrawals, etc.), these changes are first recorded in the realm's local subtree. Each realm then generates proofs (GUTA aka global user tree aggregation proofs) that demonstrate the validity of these changes. The final proof generated by the realm for each block is sent to the coordinator node. The proof sent to the coordinator proves that the "realm root", ie. the root of the subtree of height R managed by the realm, has updated legally from
an old value to a new value. This proof has a header which includes a SubTreeNodeStateTransition which specifies the old and new values of the realm root, along with the index and level of the node which it proves updates the global user state tree. For our convention, we use level = 0 for the root of the entire global user tree, and level = H for the leaves, and level = R for the realm roots.
The proofs sent to the coordinator are always for nodes at level R of the global user state tree.

The coordinator node takes the proofs and aggregates them into a single proof that the root of the entire global user state tree has updated legally from an old value to a new value.
This is done by building a tree of recursive zero knowledge proofs, where each proof in the tree proves that two child nodes have updated legally to a parent node.
In addition to this kind of proof, we also have "linear proofs" where you prove that a node in the global user state tree has updated from an old_value -> intermediate_value -> new_value.
This is accomplished by proving two state transitions which are "back to back" (ie. state_transition_1.new_value == state_transition_2.old_value). The resulting proof of these "linear proofs" is a new proof which proves that the node has update from state_transition_1.old_value -> state_transition_2.new_value.

For the incoming proofs from realms, since they are always for nodes at level R of the global user state tree, we need to promote them to proofs which prove the root level (level 0) has updated.
We do this by using DeltaMerkleProofs which prove that, if we update the realm root node of the incoming realm proof from old_value -> new_value, the global user state tree transition from old_root to new_root.
In a GUTATwoGUTA proof, we take two child realm proofs and use DeltaMerkleProofs to proof that the root of the tree updates from DMP_A.old_root -> DMP_A.new_root == DMP_B.old_root -> DMP_B.new_root.
If one of child proofs are synced to an older checkpoint/block we need to "upgrade" it using a historical merkle proof in the checkpoint tree, a tree of checkpoint leaves which store the global state roots at each block.
With a historical merkle proof, we prove that, if you make all the right hand siblings along the merkle path and compute the merkle root, you get the checkpoint tree root in the child proof from the realm, but if you leave the siblings as they are provided, you get the current latest checkpoint root, proving that the child proofs are synced to a valid checkpoint in the history.

The output of GUTATwoGUTA proofs is a proof that the ROOT of the global user state tree has updated from old_root -> new_root.
If we have two proofs which prove that the same node in the global user state tree has updated from old_value -> intermediate_value and intermediate_value -> new_value, we can use a GUTAVerifyTwoGUTALinear proof to prove that the node has updated from old_value -> new_value.

If we have an odd number of realm input proofs, we can first aggregate the even number of proofs into GUTATwoGUTA proofs, and then combine the remaining proof with the top level proof using a GUTAVerifyLeftLinearRightLeafUpgradeCheckpoint proof, which combines a linear proof with a leaf proof.

If we have two GUTAVerifyTwoGUTALinear proofs which prove that the same node in the global user state tree has updated from old_value -> intermediate_value and intermediate_value -> new_value, we can use a GUTAVerifyTwoGUTALinear proof to further aggregate the proofs.

If we only have one realm input proof, we can use a GUTAVerifyToCapWithCheckpointUpgrade proof to promote it to a root level proof and ensure its checkpoint root is upgraded to the latest checkpoint root.

For N input proofs, we want to build a recursive tree of proofs of at most height log2_ceil(N), where each level can be processed in parallel.





*/

#[cfg(test)]
mod tests {

    use std::{ops::Sub, sync::Arc, time::Duration};

    use dashmap::DashMap;
    use parth_common::memory_stores::{
        dash_tree_append_only::PsyDashMemoryAppendOnlyMerkleStore, mem_tree_recorder::SimpleMemoryMerkleRecorderStore,
        traits::PsyMemoryMerkleStoreImm,
    };
    use parth_core::{
        crypto::hash::{merkle_proof::DeltaMerkleProofCore, traits::{FieldQHasher, MerkleZeroHasher, QFieldHashable, ZeroableHash}},
        felt::{FromPrimitiveValuesFelt, ZeroableFelt},
        node::realm_identifier::QRealmIdentifier,
        pgoldilocks::PoseidonHasher,
        utils::{QPGenRandom, math::log2_ceil},
    };
    use psy_core::job::{
        self,
        job_id::{ProvingJobCircuitType, ProvingJobDataType, QJobTopic, QProvingJobDataID},
    };
    use psy_data::{
        guta::{
            header::GlobalUserTreeAggregatorHeader,
            header_extended::{GlobalUserTreeAggregatorHeaderWithJobId, GlobalUserTreeAggregatorHeaderWithTagValue, GlobalUserTreeAggregatorHeaderWithTagValueAndJobID},
            stats::GUTAStats,
            sub_tree_transition::SubTreeNodeStateTransition,
        }, proof_input::guta::{GUTANoChangeFullInput, GUTAVerifyLeftLinearRightLeafUpgradeCheckpointCircuitInput, GUTAVerifyTwoGUTACircuitInputV2, GUTAVerifyTwoGUTALinearCircuitInput, GUTAVerifyTwoGUTAUpgradeCheckpointCircuitInputV2, VerifyGUTAToCapUpgradeCheckpointCircuitInputSimple}, v1::qdata::{
            checkpoint::{PQEDCheckpointGlobalStateRoots, PQEDCheckpointLeaf, PQEDCheckpointLeafCompact, PQEDCheckpointLeafStats},
            pm_jobs_completed_stats::PPMJobsCompletedStats,
            pm_rewards_commitment::PPMRewardCommitment,
        }, worker::{metadata::PROOF_REWARD_TREE_HASH_MODE_NO_HASH_CHILDREN, metadata_with_job_id::PsyProvingJobMetadataWithJobId}
    };
    use psy_node_core::{memory_stores::simple_memory_temp_store::SimpleMemoryTempStore, psy_temp_db::StandardProcessorTempDBStoreBase};
    use psy_serialize::PsyCanonicalDatabaseSerializeBaseSingle;
    use rand::Rng;
    use rayon::result;

    use crate::guta_planner::cgp::CoordinatorGUTAPlanner;

    type F = parth_core::PF;
    type Hash = parth_core::PHash;
    type Hasher = PoseidonHasher;
    const REALM_LEVEL: usize = 12;
    const REALM_LEVEL_U8: u8 = REALM_LEVEL as u8;
    struct JobCorrectnessChecker {
        pub jobs: Vec<Vec<PsyProvingJobMetadataWithJobId<Hash, QProvingJobDataID>>>,
        pub job_witness_transitions: DashMap<QProvingJobDataID, SubTreeNodeStateTransition<F, Hash>>,
    }
    impl JobCorrectnessChecker {
        pub fn new(input_jobs: Vec<PsyProvingJobMetadataWithJobId<Hash, QProvingJobDataID>>, result_jobs: Vec<Vec<PsyProvingJobMetadataWithJobId<Hash, QProvingJobDataID>>>) -> Self {
            Self { jobs: [vec![input_jobs], result_jobs].concat(), job_witness_transitions: DashMap::new() }
        }
        pub fn get_job_level_index_by_id(
            &self,
            job_id: &QProvingJobDataID,
        ) -> anyhow::Result<(usize, usize, &PsyProvingJobMetadataWithJobId<Hash, QProvingJobDataID>)> {
            for (level_index, level_jobs) in self.jobs.iter().enumerate() {
                for (job_index, job_metadata) in level_jobs.iter().enumerate() {
                    if &job_metadata.job_id == job_id {
                        return Ok((level_index, job_index, job_metadata));
                    }
                }
            }
            Err(anyhow::anyhow!("Job id {:?} not found in planner", job_id))
        }
        pub fn is_job_input_proof(&self, job_id: &QProvingJobDataID) -> anyhow::Result<bool> {
            if job_id.circuit_type == ProvingJobCircuitType::GUTATwoEndCap {
                return Ok(true);
            }else{
                return Ok(false);
            }
        }
        pub fn process_job_witness<'a, TempStore>(
            &'a self,
            realm_identifier: &'a QRealmIdentifier,
            unique_pending_id: u64,
            temp_store: Arc<TempStore>,
            job_id: QProvingJobDataID,
            guta_circuit_whitelist: Hash,
        ) -> std::pin::Pin<Box<dyn std::future::Future<Output = anyhow::Result<SubTreeNodeStateTransition<F, Hash>>> + Send + 'a>>
        where
            TempStore: StandardProcessorTempDBStoreBase<QProvingJobDataID, Hash> + Send + Sync + 'a,
        {
            Box::pin(async move {
                let data: Vec<u8> = temp_store.get_tdb_proof_witness_bytes(realm_identifier, unique_pending_id, job_id).await?;
                let (state_transition, computed_public_inputs_hash) = match job_id.circuit_type {
                    ProvingJobCircuitType::GUTATwoGUTA => {
                        let witness = GUTAVerifyTwoGUTACircuitInputV2::<F, Hash>::psy_ser_from_slice(&data)?;
                        (witness.get_new_guta_header().state_transition, witness.get_public_inputs_hash_no_rewards_tag::<Hasher>())
                    },
                    ProvingJobCircuitType::GUTANoChange => {
                        let witness: GUTANoChangeFullInput<Hash> = GUTANoChangeFullInput::<Hash>::psy_ser_from_slice(&data)?;
                        (
                            SubTreeNodeStateTransition {
                                old_node_value: witness.checkpoint_leaf.global_state_roots.user_tree_root,
                                new_node_value: witness.checkpoint_leaf.global_state_roots.user_tree_root,
                                node_index: F::ZERO_VALUE,
                                node_level: F::ZERO_VALUE,
                            },
                            witness.get_public_inputs_hash_no_rewards_tag::<F, Hasher>(guta_circuit_whitelist)
                        )
                    },
                    ProvingJobCircuitType::GUTATwoGUTAWithCheckpointUpgrade => {
                        let witness = GUTAVerifyTwoGUTAUpgradeCheckpointCircuitInputV2::<F, Hash>::psy_ser_from_slice(&data)?;
                        (witness.get_new_guta_header().state_transition, witness.get_public_inputs_hash_no_rewards_tag::<Hasher>())
                    },
                    ProvingJobCircuitType::GUTAVerifyToCapWithCheckpointUpgrade => {
                        let witness = VerifyGUTAToCapUpgradeCheckpointCircuitInputSimple::<F, Hash>::psy_ser_from_slice(&data)?;
                        (witness.get_new_guta_header::<Hasher>().state_transition, witness.get_public_inputs_hash_no_rewards_tag::<Hasher>())
                    },
                    ProvingJobCircuitType::GUTATwoGUTALinear => {
                        let witness = GUTAVerifyTwoGUTALinearCircuitInput::<F, Hash>::psy_ser_from_slice(&data)?;
                        (witness.get_new_guta_header().state_transition, witness.get_public_inputs_hash_no_rewards_tag::<Hasher>())
                    },
                    ProvingJobCircuitType::GUTAVerifyLeftLinearRightLeafUpgradeCheckpoint => {
                        let witness = GUTAVerifyLeftLinearRightLeafUpgradeCheckpointCircuitInput::<F, Hash>::psy_ser_from_slice(&data)?;
                        (witness.get_new_guta_header().state_transition, witness.get_public_inputs_hash_no_rewards_tag::<Hasher>())
                    },
                    _ => {
                        return Err(anyhow::anyhow!("Unsupported job circuit type {:?}", job_id.circuit_type));
                    }
                };
                self.job_witness_transitions.insert(job_id, state_transition.clone());
                let job = self.get_job_level_index_by_id(&job_id)?.2;
                let expected_public_inputs_hash = job.metadata.expected_public_inputs_hash;
                if computed_public_inputs_hash != expected_public_inputs_hash {
                    return Err(anyhow::anyhow!(
                        "Job {:?} public inputs hash mismatch: computed {:?}, expected {:?}",
                        job_id,
                        computed_public_inputs_hash,
                        expected_public_inputs_hash
                    ));
                }

                if job.metadata.dependencies.len() == 2 {
                    let is_left_input_child_proof = self.is_job_input_proof(&job.metadata.dependencies[0])?;
                    let is_right_input_child_proof = self.is_job_input_proof(&job.metadata.dependencies[1])?;
                    if !is_left_input_child_proof {
                        let left_child_state_transition = self.process_job_witness(
                            realm_identifier,
                            unique_pending_id,
                            temp_store.clone(),
                            job.metadata.dependencies[0].clone(),
                            guta_circuit_whitelist.clone(),
                        ).await?;
                        if left_child_state_transition.node_index != state_transition.node_index {
                            return Err(anyhow::anyhow!(
                                "Linear Job {:?} left child node index mismatch: child {:?}, parent {:?}",
                                job_id,
                                left_child_state_transition.node_index,
                                state_transition.node_index
                            ));
                        } else if left_child_state_transition.node_level != state_transition.node_level {
                            return Err(anyhow::anyhow!(
                                "Linear Job {:?} left child node level mismatch: child {:?}, parent {:?}",
                                job_id,
                                left_child_state_transition.node_level,
                                state_transition.node_level
                            ));
                        } else if left_child_state_transition.old_node_value != state_transition.old_node_value {
                            return Err(anyhow::anyhow!(
                                "Linear Job {:?} left child old node value mismatch: child {:?}, parent {:?}",
                                job_id,
                                left_child_state_transition.old_node_value,
                                state_transition.old_node_value
                            ));
                        }
                        if !is_right_input_child_proof {
                            let right_child_state_transition = self.process_job_witness(
                                realm_identifier,
                                unique_pending_id,
                                    temp_store.clone(),
                                job.metadata.dependencies[1].clone(),
                                guta_circuit_whitelist.clone(),
                            ).await?;
                            if right_child_state_transition.node_index != state_transition.node_index {
                                return Err(anyhow::anyhow!(
                                    "Linear Job {:?} right child node index mismatch: child {:?}, parent {:?}",
                                    job_id,
                                    right_child_state_transition.node_index,
                                    state_transition.node_index
                                ));
                            } else if right_child_state_transition.node_level != state_transition.node_level {
                                return Err(anyhow::anyhow!(
                                    "Linear Job {:?} right child node level mismatch: child {:?}, parent {:?}",
                                    job_id,
                                    right_child_state_transition.node_level,
                                    state_transition.node_level
                                ));
                            } else if right_child_state_transition.old_node_value != left_child_state_transition.new_node_value {
                                return Err(anyhow::anyhow!(
                                    "Linear Job {:?} is not back to back, left.new_node_value {:?} != right.old_node_value {:?}",
                                    job_id,
                                    left_child_state_transition.new_node_value,
                                    right_child_state_transition.old_node_value
                                ));
                            } else if right_child_state_transition.new_node_value != state_transition.new_node_value {
                                return Err(anyhow::anyhow!(
                                    "Linear Job {:?} right child new node value mismatch: child {:?}, parent {:?}",
                                    job_id,
                                    right_child_state_transition.new_node_value,
                                    state_transition.new_node_value
                                ));
                            }
                        } else {
                            // No-op for else branch
                        }
                    }
                }
                Ok(state_transition)
            })
        }
        pub fn check_jobs_correctness<Hasher: FieldQHasher<F, Hash>>(&self) -> anyhow::Result<()> {
            for level in 1..self.jobs.len() {
                for job_metadata in &self.jobs[level] {
                    for (dep_index, dep_job_id) in job_metadata.metadata.dependencies.iter().enumerate() {
                        let (dep_level, _, dep_job_metadata) = self.get_job_level_index_by_id(dep_job_id)?;
                        if dep_level >= level {
                            return Err(anyhow::anyhow!(
                                "Job {:?} at level {} depends on job {:?} at level {} which is not lower",
                                job_metadata.job_id,
                                level,
                                dep_job_id,
                                dep_level
                            ));
                        }
                        let is_dep_input_proof = self.is_job_input_proof(dep_job_id)?;
                        let expected_rewards_tree_node_level = job_metadata.metadata.reward_tree_node_level + 1;
                        let expected_rewards_tree_node_index = (job_metadata.metadata.reward_tree_node_index << 1) | (dep_index as u64);
                        if dep_job_metadata.metadata.reward_tree_node_level != expected_rewards_tree_node_level && !is_dep_input_proof{
                            return Err(anyhow::anyhow!(
                                "Job {:?} at level {} depends on job {:?} at level {} which has incorrect reward tree node level {}, expected {}",
                                job_metadata.job_id,
                                level,
                                dep_job_id,
                                dep_level,
                                dep_job_metadata.metadata.reward_tree_node_level,
                                expected_rewards_tree_node_level
                            ));
                        }
                        if dep_job_metadata.metadata.reward_tree_node_index != expected_rewards_tree_node_index && !is_dep_input_proof {
                            return Err(anyhow::anyhow!(
                                "Job {:?} at level {} depends on job {:?} at level {} which has incorrect reward tree node index {}, expected {}",
                                job_metadata.job_id,
                                level,
                                dep_job_id,
                                dep_level,
                                dep_job_metadata.metadata.reward_tree_node_index,
                                expected_rewards_tree_node_index
                            ));
                        }
                    }

                    if job_metadata.metadata.dependencies.len() == 2 {
                        let left_dep = &job_metadata.metadata.dependencies[0];
                        let right_dep = &job_metadata.metadata.dependencies[1];
                        let left_is_input_proof = self.is_job_input_proof(left_dep)?;
                        let right_is_input_proof = self.is_job_input_proof(right_dep)?;
                        let left_needs_checkpoint_upgrade = left_is_input_proof && left_dep.goal_id == 0;
                        let right_needs_checkpoint_upgrade = right_is_input_proof && right_dep.goal_id == 0;
                        let parent_job_circuit_type = job_metadata.job_id.circuit_type;
                        if left_is_input_proof && right_is_input_proof {
                            if parent_job_circuit_type == ProvingJobCircuitType::GUTATwoGUTA {
                                if left_needs_checkpoint_upgrade || right_needs_checkpoint_upgrade {
                                    return Err(anyhow::anyhow!(
                                        "Job {:?} is GUTATwoGUTA but one of its input proofs needs checkpoint upgrade",
                                        job_metadata.job_id
                                    ));
                                }
                            } else if parent_job_circuit_type == ProvingJobCircuitType::GUTATwoGUTAWithCheckpointUpgrade {
                                if !left_needs_checkpoint_upgrade && !right_needs_checkpoint_upgrade {
                                    return Err(anyhow::anyhow!(
                                        "Job {:?} is GUTATwoGUTAWithCheckpointUpgrade but none of its input proofs needs checkpoint upgrade",
                                        job_metadata.job_id
                                    ));
                                }
                            } else {
                                return Err(anyhow::anyhow!(
                                    "Job {:?} has unexpected circuit type {:?} for two input proofs",
                                    job_metadata.job_id,
                                    parent_job_circuit_type
                                ));
                            }
                        } else if left_is_input_proof && !right_is_input_proof {
                            anyhow::bail!(
                                "Job {:?} has left input proof as input proof but right is not, which is unexpected",
                                job_metadata.job_id
                            );
                        } else if !left_is_input_proof && right_is_input_proof {
                            if parent_job_circuit_type != ProvingJobCircuitType::GUTAVerifyLeftLinearRightLeafUpgradeCheckpoint {
                                return Err(anyhow::anyhow!(
                                    "Job {:?} has right input proof as input proof but left is not, expected circuit type GUTAVerifyLeftLinearRightLeafUpgradeCheckpoint but got {:?}",
                                    job_metadata.job_id,
                                    parent_job_circuit_type
                                ));
                            }
                        } else {
                            // Both are non-input proofs
                            if parent_job_circuit_type != ProvingJobCircuitType::GUTATwoGUTALinear {
                                return Err(anyhow::anyhow!(
                                    "Job {:?} has two non-input proofs but unexpected circuit type {:?}",
                                    job_metadata.job_id,
                                    parent_job_circuit_type
                                ));
                            }
                        }
                    } else if job_metadata.metadata.dependencies.len() == 1 {
                        let dep = &job_metadata.metadata.dependencies[0];
                        let dep_is_input_proof = self.is_job_input_proof(dep)?;
                        let dep_needs_checkpoint_upgrade = dep_is_input_proof && dep.goal_id == 0;
                        let parent_job_circuit_type = job_metadata.job_id.circuit_type;
                        if dep_is_input_proof {
                            if parent_job_circuit_type == ProvingJobCircuitType::GUTAVerifyToCapWithCheckpointUpgrade {
                                if !dep_is_input_proof {
                                    return Err(anyhow::anyhow!(
                                        "Job {:?} is GUTAVerifyToCapWithCheckpointUpgrade but its input proof does not need checkpoint upgrade",
                                        job_metadata.job_id
                                    ));
                                }
                            } else {
                                return Err(anyhow::anyhow!(
                                    "Job {:?} has unexpected circuit type {:?} for single input proof",
                                    job_metadata.job_id,
                                    parent_job_circuit_type
                                ));
                            }
                        } else {
                            return Err(anyhow::anyhow!(
                                "Job {:?} has non-input proof as single dependency, which is unexpected",
                                job_metadata.job_id
                            ));
                        }
                    } else {
                        if job_metadata.job_id.circuit_type != ProvingJobCircuitType::GUTANoChange {
                            return Err(anyhow::anyhow!(
                                "Job {:?} has {} dependencies, expected 1 or 2 or 0 for no change proof",
                                job_metadata.job_id,
                                job_metadata.metadata.dependencies.len()
                            ));
                        } else if job_metadata.metadata.dependencies.len() != 0 {
                            return Err(anyhow::anyhow!(
                                "Job {:?} is GUTANoChange but has {} dependencies, expected 0",
                                job_metadata.job_id,
                                job_metadata.metadata.dependencies.len()
                            ));
                        }
                    }
                }
            }

            Ok(())
        }pub fn generate_graph_viz(&self) -> anyhow::Result<String> {
            use std::fmt::Write;

            let mut dot = String::new();
            writeln!(dot, "digraph G {{")?;

            // 1. Global Graph Attributes
            // BT = Bottom to Top. Since Level 0 are inputs and Level N is root,
            // this puts inputs at the bottom and root at the top.
            writeln!(dot, "  rankdir=BT;")?; 
            writeln!(dot, "  compound=true;")?;
            writeln!(dot, "  splines=ortho;")?; // Circuit-board style lines
            writeln!(dot, "  nodesep=0.4;")?;
            writeln!(dot, "  ranksep=0.6;")?;
            writeln!(dot, "  fontname=\"Courier\";")?; // Monospace for a technical look
            writeln!(dot, "  node [shape=plain, fontname=\"Courier\", fontsize=10];")?;
            writeln!(dot, "  edge [color=\"black\", arrowhead=vee, penwidth=1.0];")?;
            writeln!(dot, "  bgcolor=\"white\";")?;

            // 2. Node Generation grouped by Levels
            for (level_idx, level_jobs) in self.jobs.iter().enumerate() {
                
                // Level Clusters: Dashed grey lines, no fill
                writeln!(dot, "  subgraph cluster_{} {{", level_idx)?;
                writeln!(dot, "    label=\"Level {}\";", level_idx)?;
                writeln!(dot, "    style=\"dashed\";")?;
                writeln!(dot, "    color=\"#555555\";")?;
                writeln!(dot, "    fontcolor=\"#555555\";")?;
                writeln!(dot, "    fontsize=10;")?;
                writeln!(dot, "    labelloc=\"b\";")?; // Label at bottom

                for (job_index, job) in level_jobs.iter().enumerate() {
                    let node_id = format!("job_{}_{}", level_idx, job_index);

                    // Extract Circuit Type for the Header
                    // We format the debug string and split it to get a cleaner display name
                    let circuit_type_debug = format!("{:?}", job.job_id.circuit_type);
                    // Optional: Cleanup "ProvingJobCircuitType::" prefix if present in debug output
                    let display_type = circuit_type_debug.replace("ProvingJobCircuitType::", "");

                    let reward_lvl = job.metadata.reward_tree_node_level;
                    let reward_idx = job.metadata.reward_tree_node_index;
                    
                    // High Contrast Node Design
                    // Header: Black BG, White Text
                    // Body: White BG, Black Text
                    writeln!(dot, "    {} [label=<", node_id)?;
                    writeln!(
                        dot,
                        "      <TABLE BORDER=\"0\" CELLBORDER=\"1\" CELLSPACING=\"0\" CELLPADDING=\"4\" BGCOLOR=\"white\" STYLE=\"ROUNDED\">"
                    )?;

                    // Header Row (Circuit Type)
                    writeln!(
                        dot, 
                        "        <TR><TD COLSPAN=\"2\" BGCOLOR=\"black\"><FONT COLOR=\"white\"><B>{}</B></FONT></TD></TR>", 
                        display_type
                    )?;

                    // Job Details
                    writeln!(dot, "        <TR>")?;
                    writeln!(dot, "          <TD ALIGN=\"LEFT\">Rwd Lvl:</TD>")?;
                    writeln!(dot, "          <TD ALIGN=\"RIGHT\">{}</TD>", reward_lvl)?;
                    writeln!(dot, "        </TR>")?;
                    writeln!(dot, "        <TR>")?;
                    writeln!(dot, "          <TD ALIGN=\"LEFT\">Rwd Idx:</TD>")?;
                    writeln!(dot, "          <TD ALIGN=\"RIGHT\">{}</TD>", reward_idx)?;
                    writeln!(dot, "        </TR>")?;

                    // Conditional: Mark Input Proofs distinctively in the text
                    if self.is_job_input_proof(&job.job_id)? {
                         writeln!(dot, "        <TR><TD COLSPAN=\"2\" ALIGN=\"CENTER\"><I>Input Leaf</I></TD></TR>")?;
                         writeln!(dot, "        <TR><TD COLSPAN=\"2\" ALIGN=\"CENTER\"><I>Checkpoint {}</I></TD></TR>", job.job_id.goal_id)?;
                    }

                    writeln!(dot, "      </TABLE>")?;
                    writeln!(dot, "    >];")?;
                }
                writeln!(dot, "  }}")?; // End subgraph
            }

            // 3. Edge Generation
            for (level_idx, level_jobs) in self.jobs.iter().enumerate() {
                for (job_index, job) in level_jobs.iter().enumerate() {
                    let parent_node_id = format!("job_{}_{}", level_idx, job_index);

                    for dep_job_id in &job.metadata.dependencies {
                        if let Ok((dep_level, dep_index, _)) = self.get_job_level_index_by_id(dep_job_id) {
                            let child_node_id = format!("job_{}_{}", dep_level, dep_index);
                            
                            // Standard edge
                            writeln!(dot, "  {} -> {};", child_node_id, parent_node_id)?;
                        } else {
                            // Error/Missing edge
                            let ghost_id = format!("missing_{:?}", dep_job_id).replace(" ", "_").replace("(", "").replace(")", "");
                            writeln!(dot, "  \"{}\" [shape=box, style=dotted, label=\"Missing\"];", ghost_id)?;
                            writeln!(dot, "  \"{}\" -> {} [style=dotted];", ghost_id, parent_node_id)?;
                        }
                    }
                }
            }

            writeln!(dot, "}}")?;
            Ok(dot)
        }
        pub fn generate_graph_viz_simple(&self) -> anyhow::Result<String> {
            use std::fmt::Write;

            let mut dot = String::new();
            writeln!(dot, "digraph G {{")?;
            
            // 1. Graph Attributes
            writeln!(dot, "  rankdir=BT;")?;
            // ordering=in ensures that the order in which we define edges entering a node 
            // (the dependencies) is respected left-to-right.
            writeln!(dot, "  ordering=in;")?; 
            writeln!(dot, "  node [shape=box, fontname=\"Courier\", fontsize=10];")?;
            writeln!(dot, "  edge [color=\"black\"];")?;

            // 2. Define Nodes and Horizontal constraints (Invisible edges)
            for (level_idx, level_jobs) in self.jobs.iter().enumerate() {
                
                // We use a subgraph with rank=same to ensure all nodes 
                // at this level stay on the same horizontal timeline.
                writeln!(dot, "  subgraph level_{} {{", level_idx)?;
                writeln!(dot, "    rank=same;")?;

                for (job_index, job) in level_jobs.iter().enumerate() {
                    let node_id = format!("job_{}_{}", level_idx, job_index);

                    let label = if level_idx == 0 {
                        format!(
                            "Input Proof {}\nCheckpoint {}", 
                            job_index + 1, 
                            job.job_id.goal_id
                        )
                    } else {
                        let circuit_type_debug = format!("{:?}", job.job_id.circuit_type);
                        let display_type = circuit_type_debug.replace("ProvingJobCircuitType::", "");

                        format!(
                            "{}\nRewardLevel={}\nRewardIndex={}\nLayer={}",
                            display_type,
                            job.metadata.reward_tree_node_level,
                            job.metadata.reward_tree_node_index,
                            level_idx
                        )
                    };

                    writeln!(dot, "    {} [label=\"{}\"];", node_id, label)?;

                    // Horizontal Constraint:
                    // Force job_N to be to the left of job_N+1 using an invisible edge.
                    // This prevents "ragged" inputs from floating to the wrong side.
                    if job_index > 0 {
                        let prev_node_id = format!("job_{}_{}", level_idx, job_index - 1);
                        writeln!(dot, "    {} -> {} [style=invis, weight=2];", prev_node_id, node_id)?;
                    }
                }
                writeln!(dot, "  }}")?; // End subgraph
            }

            // 3. Define Logic Edges (Dependencies)
            // We do this in a separate pass or block to ensure the nodes are already placed in ranks.
            for (level_idx, level_jobs) in self.jobs.iter().enumerate() {
                for (job_index, job) in level_jobs.iter().enumerate() {
                    let node_id = format!("job_{}_{}", level_idx, job_index);

                    for dep_job_id in &job.metadata.dependencies {
                        if let Ok((dep_level, dep_index, _)) = self.get_job_level_index_by_id(dep_job_id) {
                            let child_node_id = format!("job_{}_{}", dep_level, dep_index);
                            writeln!(dot, "  {} -> {};", child_node_id, node_id)?;
                        } else {
                            let missing_id = format!("missing_{}_{}", level_idx, job_index);
                            writeln!(dot, "  {} [label=\"Missing\" style=dotted];", missing_id)?;
                            writeln!(dot, "  {} -> {} [style=dotted];", missing_id, node_id)?;
                        }
                    }
                }
            }

            writeln!(dot, "}}")?;
            Ok(dot)
        }
    }
    fn gen_random_checkpoint() -> (
        Hash,
        PQEDCheckpointLeaf<F, Hash>,
        PQEDCheckpointLeafStats<F, Hash>,
        PQEDCheckpointGlobalStateRoots<Hash>,
        PQEDCheckpointLeafCompact<Hash>,
    ) {
        let stats = PQEDCheckpointLeafStats::<F, Hash> {
            fees_collected: F::from_u64_value(u64::qp_rand_gen()),
            user_ops_processed: F::from_u64_value(u64::qp_rand_gen()),
            total_transactions: F::from_u64_value(u64::qp_rand_gen()),
            slots_modified: F::from_u64_value(u64::qp_rand_gen()),
            pm_jobs_completed: PPMJobsCompletedStats {
                deploy_contracts_completed: F::from_u64_value(u64::qp_rand_gen()),
                register_users_completed: F::from_u64_value(u64::qp_rand_gen()),
                gutas_completed: F::from_u64_value(u64::qp_rand_gen()),
            },
            block_time: F::from_u64_value(u64::qp_rand_gen()),
            random_seed: Hash::rand(),
            pm_rewards_commitment: PPMRewardCommitment {
                register_users_root: Hash::rand(),
                gutas_root: Hash::rand(),
                deploy_contracts_root: Hash::rand(),
            },
            da_challenges_claimed: [F::ZERO_VALUE; 14],
        };
        let stats_hash = stats.qfhash::<Hasher>();
        let checkpoint_global_state_roots = PQEDCheckpointGlobalStateRoots::<Hash> {
            contract_tree_root: Hash::rand(),
            deposit_tree_root: Hash::rand(),
            user_tree_root: Hash::rand(),
            withdrawal_tree_root: Hash::rand(),
            user_registration_tree_root: Hash::rand(),
        };
        let global_chain_root = checkpoint_global_state_roots.qfhash::<Hasher>();
        let checkpoint_leaf = PQEDCheckpointLeaf {
            global_chain_root,
            stats: stats.clone(),
        };
        let checkpoint_leaf_compact = PQEDCheckpointLeafCompact {
            global_chain_root,
            stats_hash,
        };
        let checkpoint_leaf_hash = checkpoint_leaf.qfhash::<Hasher>();
        (
            checkpoint_leaf_hash,
            checkpoint_leaf,
            stats,
            checkpoint_global_state_roots,
            checkpoint_leaf_compact,
        )
    }

    fn gen_job_for_index_checkpoint(
        checkpoint_id: u64,
        index: u64,
        checkpoint_tree_root: Hash,
    ) -> GlobalUserTreeAggregatorHeaderWithTagValueAndJobID<F, Hash> {
        GlobalUserTreeAggregatorHeaderWithTagValueAndJobID {
            header: GlobalUserTreeAggregatorHeaderWithTagValue {
                header: GlobalUserTreeAggregatorHeader {
                    guta_circuit_whitelist: Hash::from_values(1, 2, 3, 4),
                    checkpoint_tree_root,
                    state_transition: SubTreeNodeStateTransition {
                        old_node_value: Hash::rand(),
                        new_node_value: Hash::rand(),
                        node_index: F::from_u64_value(index),
                        node_level: F::from_u8_value(REALM_LEVEL_U8),
                    },
                    stats: GUTAStats {
                        fees_collected: F::from_u64_value(u64::qp_rand_gen()),
                        user_ops_processed: F::from_u64_value(u64::qp_rand_gen()),
                        total_transactions: F::from_u64_value(u64::qp_rand_gen()),
                        slots_modified: F::from_u64_value(u64::qp_rand_gen()),
                    },
                    total_aggregation_proofs_generated: F::from_u8_value(0),
                },
                new_tag_tree_node_value: Hash::rand(),
            },
            job_id: QProvingJobDataID::new(
                QJobTopic::GenerateStandardProof,
                checkpoint_id,
                u32::qp_rand_gen(),
                u32::qp_rand_gen(),
                index as u32,
                ProvingJobCircuitType::GUTATwoEndCap,
                ProvingJobDataType::OutputProof,
                0,
            ),
        }
    }

    fn gen_rand_unique_array_of_u64s_in_range(len: usize, range_start: u64, range_end: u64) -> Vec<u64> {
        if len as u64 > (range_end - range_start) {
            panic!("Cannot generate {} unique values in range {}..{}", len, range_start, range_end);
        }
        use std::collections::HashSet;
        let mut set = HashSet::new();
        let mut rng = rand::thread_rng();
        while set.len() < len {
            let val = rng.gen_range(range_start..range_end);
            set.insert(val);
        }
        set.into_iter().collect()
    }
    fn get_job_metadata_for_input_jobs(input_jobs: &[GlobalUserTreeAggregatorHeaderWithTagValueAndJobID<F, Hash>]) -> Vec<PsyProvingJobMetadataWithJobId<Hash, QProvingJobDataID>> {
        input_jobs
            .iter()
            .map(|job_header_with_id| {
                GlobalUserTreeAggregatorHeaderWithJobId {
                    header: job_header_with_id.header.header.clone(),
                    job_id: job_header_with_id.job_id.clone(),
                }.to_metadata_with_job_standard_children::<Hasher>(vec![])
            })
            .collect()
    }

    async fn test_n_jobs(input_jobs_count: usize) -> anyhow::Result<()> {
        let realm_identifier = QRealmIdentifier {
            realm_id: 1,
            realm_sub_id: 0,
        };
        let temp_store = Arc::new(SimpleMemoryTempStore::new());
        let unique_pending_id = 0u64;
        let global_user_tree_height = REALM_LEVEL_U8;
        let checkpoint_tree = PsyDashMemoryAppendOnlyMerkleStore::<Hasher, Hash>::new(32);
        let mut global_user_tree = SimpleMemoryMerkleRecorderStore::<Hasher, Hash>::new(global_user_tree_height);

        let (checkpoint_0_leaf_hash, checkpoint_0_leaf, _stats_0, _global_state_roots_0, _checkpoint_0_leaf_compact) = gen_random_checkpoint();
        checkpoint_tree.append_leaf(0, checkpoint_0_leaf_hash)?;

        let checkpoint_0_root = checkpoint_tree.get_root();
        let (checkpoint_1_leaf_hash, checkpoint_1_leaf, stats_1, global_state_roots_1, checkpoint_1_leaf_compact) = gen_random_checkpoint();
        checkpoint_tree.append_leaf(1, checkpoint_1_leaf_hash)?;
        let checkpoint_1_root = checkpoint_tree.get_root();

        let jobs = gen_rand_unique_array_of_u64s_in_range(input_jobs_count, 0, 1u64 << REALM_LEVEL_U8)
            .into_iter()
            .map(|index| {
                if (u8::qp_rand_gen() & 1) == 1 {
                    gen_job_for_index_checkpoint(1, index, checkpoint_1_root)
                } else {
                    gen_job_for_index_checkpoint(0, index, checkpoint_0_root)
                }
            })
            .collect::<Vec<_>>();
        let total_input_jobs = jobs.len();

        let mut planner = CoordinatorGUTAPlanner::<F, Hash>::new();
        for job in &jobs {
            planner
                .add_realm_job::<Hasher, SimpleMemoryTempStore>(
                    unique_pending_id,
                    &checkpoint_0_root,
                    &checkpoint_tree,
                    &mut global_user_tree,
                    temp_store.clone(),
                    job,
                )
                .await?;
        }

        let current_checkpoint_root = checkpoint_1_root;
        let reward_tree_root_level = 2u8;
        let reward_tree_root_index = 0u64;
        let most_recent_checkpoint_global_state_roots = global_state_roots_1;
        let most_recent_checkpoint_stats_hash = stats_1.qfhash::<Hasher>();
        let guta_circuit_whitelist = Hash::from_values(1, 2, 3, 4);

        let result = planner
            .finalize_with_reward_ids(
                &realm_identifier,
                unique_pending_id,
                &current_checkpoint_root,
                &checkpoint_tree,
                &mut global_user_tree,
                temp_store.clone(),
                reward_tree_root_level,
                reward_tree_root_index,
                most_recent_checkpoint_global_state_roots,
                most_recent_checkpoint_stats_hash,
                guta_circuit_whitelist,
            )
            .await?;
        let root_job_id = result
            .last()
            .and_then(|level| level.first())
            .map(|job_metadata| job_metadata.job_id.clone())
            .ok_or_else(|| anyhow::anyhow!("No root job generated"))?;
        // NOTE: finalize_with_reward_ids must only return the new jobs created, not the input jobs, as the return value are the jobs which are pushed to the worker queue
        let input_jobs_metadata = get_job_metadata_for_input_jobs(&jobs);
        let correctness_checker = JobCorrectnessChecker::new(input_jobs_metadata, result);
        println!("Generated Job Levels: {}", correctness_checker.jobs.len());
        println!("graph viz:\n{}", correctness_checker.generate_graph_viz_simple()?);

        correctness_checker.check_jobs_correctness::<Hasher>()?;
        // add one level for the children input jobs we prepend to the result jobs from CoordinatorGUTAPlanner
        let expected_levels = if total_input_jobs <= 1 { 1 } else { log2_ceil(total_input_jobs) } + 1;
        if correctness_checker.jobs.len() > expected_levels {
            return Err(anyhow::anyhow!(
                "Expected at most {} levels, got {} levels",
                expected_levels,
                correctness_checker.jobs.len()
            ));
        }
        println!("Root Job ID: {:?}", root_job_id);
        correctness_checker.process_job_witness::<SimpleMemoryTempStore>(&realm_identifier, unique_pending_id, temp_store.clone(), root_job_id, guta_circuit_whitelist).await?;

        Ok(())
    }
    #[tokio::test]
    async fn demonstration_of_basic_functionality_you_need_to_make_tests() {
        let mut has_error = false;
        for i in 0..12 {
            println!("Testing with {} input jobs...", i);
            let result = test_n_jobs(i).await;
            if result.is_err() {
                has_error = true;
                println!("Test failed: {:?}", result.err());
            }
        }
        if has_error {
            panic!("Some tests failed, see output above.");
        }
    }
}

