

use std::hash::Hash;

use anyhow::Result;
use serde::{de::DeserializeOwned, Deserialize, Serialize};
use serde_repr::{Deserialize_repr, Serialize_repr};
use strum_macros::{Display, FromRepr};

use crate::common::traits::{merkle::{MerkleHasher, MerkleZeroHasher, ZeroableHash}, serializable::QPDSerializable};
pub trait QHashBase: PartialEq + ZeroableHash + Copy + Serialize + DeserializeOwned + QPDSerializable {}
pub trait QProofBase: PartialEq + Clone + Serialize + DeserializeOwned + QPDSerializable {}


pub trait QHashable<Hash: QHashBase> {
    fn get_q_hash<QH: QHasher<Hash>>(&self) -> Hash;
}
pub trait QHasher<Hash: QHashBase>: MerkleHasher<Hash> + MerkleZeroHasher<Hash> {
    fn q_hash<T: QHashable<Hash>>(target: &T) -> Hash;
}

#[derive(Clone, PartialEq, Eq, Debug, Serialize, Deserialize, Copy)]
#[serde(bound = "for<'de2> Hash: Deserialize<'de2>")]
pub struct QParthProofPublicInputsPreimage<Hash: QHashBase> {
    pub index: u64, // this index of the node in the merkle tree that this proof is proving updates to
    pub level: u8, // the level of the node in the merkle tree that this proof is proving updates to, 0 = root, tree_height = leaf
    pub old_node_value: Hash, // the old value of the node in the merkle tree that this proof proves an update to
    pub new_node_value: Hash, // the new value of the node in the merkle tree that this proof proves an update to
    pub rewards_hash_commitment: Hash, // hash(hash_two_to_one(left_child_reward_commitment, right_child_reward_commitment), new_reward_info_hash), for end cap proofs this is the zero hash
    pub checkpoint_tree_root: Hash, // hash of the checkpoint tree root that this operation is synced to, "the state of the block chain that this proof is aware of"
    pub total_guta_proofs_generated: u64, // total proofs generated by miners to get to this point, for end cap proofs this is 0, for guta proofs this is the sum of the two child proofs + 1
    pub total_user_updates: u64, // total user updates that have happened in the tree up to and including this proof, for end cap proofs this is 1, for guta proofs this is the sum of the two child proofs
    pub total_fees_paid: u64, // total fees paid by users in the tree up to and including this proof, for end cap proofs this is the fee paid by the user, for guta proofs this is the sum of the two child proofs
}

impl<Hash: QHashBase> QParthProofPublicInputsPreimage<Hash> {
    pub fn get_combined_preimage(left: &Self, right: &Self, new_rewards_hash_commitment: Hash, old_node_value: Hash, new_node_value: Hash, level: u8, index: u64, checkpoint_tree_root: Hash) -> Self {
        Self {
            index,
            level,
            old_node_value,
            new_node_value,
            rewards_hash_commitment: new_rewards_hash_commitment,
            checkpoint_tree_root,
            total_guta_proofs_generated: left.total_guta_proofs_generated + right.total_guta_proofs_generated + 1,
            total_user_updates: left.total_user_updates + right.total_user_updates,
            total_fees_paid: left.total_fees_paid + right.total_fees_paid,
        }
    }
}

pub trait QHasherBase<Hash: QHashBase, Proof: QProofBase>: QHasher<Hash> {
    fn get_proof_public_input(proof: &Proof) -> Hash; // the public inputs of the proof is a hash which is the hash of the QParthProofPublicInputsPreimage
    fn hash_proof_public_inputs_preimage(preimage: &QParthProofPublicInputsPreimage<Hash>) -> Hash;
}

pub trait QZKProofVerifier<Hash: QHashBase, Proof: QProofBase>: QHasherBase<Hash, Proof> {
    fn verify_zk_proof(&self, circuit_type: ProvingJobCircuitType, proof: &Proof) -> bool;
    fn verify_zk_proof_and_check_public_inputs(&self, circuit_type: ProvingJobCircuitType, proof: &Proof, public_inputs_preimage: &QParthProofPublicInputsPreimage<Hash>) -> bool {
        let public_inputs = Self::get_proof_public_input(proof);
        if public_inputs != Self::hash_proof_public_inputs_preimage(public_inputs_preimage) {
            return false;
        }
        self.verify_zk_proof(circuit_type, proof)
    }
}

pub trait QNetworkTypesConfigBase {
    type QHash: QHashBase;
    type ZKProof: QProofBase;
    type HasherBase: QHasherBase<Self::QHash, Self::ZKProof>;
    const GLOBAL_USER_TREE_HEIGHT: u8; // the height of the global user tree, ie. the full merkle tree that can hold all users
    const COORDINATOR_GLOBAL_USER_TREE_HEIGHT: u8; // the height of the global user tree stored in the coordinator (ie. the upper half of the merkle tree)
    const REALM_GLOBAL_USER_TREE_HEIGHT: u8; // the height of the global user tree stored in each realm (ie. the height of the sub-trees stored in each realm == GLOBAL_USER_TREE_HEIGHT - COORDINATOR_GLOBAL_USER_TREE_HEIGHT)
    const MAX_USERS: u64; // = 2**GLOBAL_USER_TREE_HEIGHT
    const MAX_REALMS: u32; // = 2**COORDINATOR_GLOBAL_USER_TREE_HEIGHT
    const MAX_USERS_PER_REALM: u32; // = 2**REALM_GLOBAL_USER_TREE_HEIGHT
}

#[derive(Serialize_repr, Deserialize_repr, PartialEq, Debug, Clone, Copy, Eq, Hash, PartialOrd, Ord, FromRepr, Display)]
#[repr(u8)]
pub enum QJobTopic {
    GenerateStandardProof = 0,
    // more to be added later
}
impl QJobTopic {
    pub fn to_u8(&self) -> u8 {
        *self as u8
    }
}
impl From<QJobTopic> for u8 {
    fn from(value: QJobTopic) -> u8 {
        value as u8
    }
}
impl TryFrom<u8> for QJobTopic {
    type Error = anyhow::Error;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
       Self::from_repr(value).ok_or_else(|| anyhow::format_err!("Invalid QJobTopic value: {}", value))
    }
}

#[derive(Serialize_repr, Deserialize_repr, PartialEq, Debug, Clone, Copy, Eq, Hash, PartialOrd, Ord, Display, FromRepr)]
#[repr(u8)]
pub enum ProvingJobDataType {
    InputWitness = 0,
    InputProof = 1,
    OutputProof = 2,
}
impl ProvingJobDataType {
    pub fn to_u8(&self) -> u8 {
        *self as u8
    }
}
impl From<ProvingJobDataType> for u8 {
    fn from(value: ProvingJobDataType) -> u8 {
        value as u8
    }
}

impl TryFrom<u8> for ProvingJobDataType {
    type Error = anyhow::Error;
    fn try_from(value: u8) -> Result<Self, Self::Error> {
        Self::from_repr(value).ok_or_else(|| anyhow::format_err!("Invalid ProvingJobDataType value: {}", value))
    }
}

#[derive(Serialize_repr, Deserialize_repr, PartialEq, Debug, Clone, Copy, Eq, Hash, PartialOrd, Ord, Display, FromRepr)]
#[repr(u8)]
pub enum ProvingJobCircuitType {
    UserEndCap = 6, // a user end cap proof, proves a user leaf node has updated from its old value to its new value
    GUTATwoEndCap = 7, // verifies two user end cap proofs to a higher node in the user state tree
    GUTATwoGUTA = 8, // verifies two GUTA proofs to a higher node in the user state tree
    GUTALeftEndCapRightGUTA = 9, // verifes a left user end cap proof and a right GUTA proof to a higher node in the user state tree
    GUTALeftGUTARightEndCap = 10, // verfifes a left GUTA proof and a right user end cap proof to a higher node in the user state tree
    GUTASingleEndCap = 11,// verfifes a single user end cap proof to a higher node in the user state tree
    GUTAVerifyToNode = 12, // verfies a single GUTA proof to a higher node in the user state tree
    GUTAOnlyRegisterUsers = 14,
    GUTANoChange = 15,

    Unknown = 255,
}

impl ProvingJobCircuitType {
    pub fn to_u8(&self) -> u8 {
        *self as u8
    }
    pub fn to_circuit_group_id(&self) -> u32 {
        (self.to_u8() as u32) + 0xCF00u32
    }
}


impl From<ProvingJobCircuitType> for u8 {
    fn from(value: ProvingJobCircuitType) -> Self {
        value as u8
    }
}
impl TryFrom<u8> for ProvingJobCircuitType {
    type Error = anyhow::Error;
    fn try_from(value: u8) -> Result<Self, Self::Error> {
        Self::from_repr(value).ok_or_else(|| anyhow::format_err!("Invalid ProvingJobCircuitType value: {}", value))
    }
}
#[derive(Serialize, Deserialize, PartialEq, Debug, Clone, Copy, Eq, Hash, PartialOrd, Ord)]
pub struct QProvingJobDataID {
    pub topic: QJobTopic, // for now, this is always GenerateStandardProof
    pub goal_id: u64, // usually the checkpoint id, not necessarily the canonical checkpoint id, just one more than the last finalized checkpoint id
    pub circuit_type: ProvingJobCircuitType, // the type of proof circuit for this job, used to determine which zkp verifier data to use for recursion
    pub group_id: u32, // for end cap proofs it is unique the realm edge api id that intakes the user end cap proof, for guta proofs it is the realm id
    pub sub_group_id: u32, // usually the level in the tree for guta proofs, 
    pub task_index: u32, // for guta proofs it is the index of the proof in the global user tree casted to a u32 for now since we only have less than 4 billion users
    pub data_type: ProvingJobDataType, // the type of data stored, can be input witness, input proof, output proof
    pub data_index: u8, // make this 0 for now 
}
impl QProvingJobDataID {
    pub fn try_from_bytes(value: &[u8]) -> anyhow::Result<Self> {
        if value.len() != 24 {
            anyhow::bail!("invalid byte length for proving job data id");
        }
        let topic: QJobTopic = value[0].try_into()?;
        let goal_id = u64::from_le_bytes(value[1..9].try_into()?);
        let circuit_type = ProvingJobCircuitType::try_from(value[9])?;
        let group_id = u32::from_le_bytes(value[10..14].try_into()?);
        let sub_group_id = u32::from_le_bytes(value[14..18].try_into()?);
        let task_index = u32::from_le_bytes(value[18..22].try_into()?);
        let data_type = ProvingJobDataType::try_from(value[22])?;
        let data_index = value[23];
        Ok(QProvingJobDataID {
            topic,
            goal_id,
            circuit_type,
            group_id,
            sub_group_id,
            task_index,
            data_type,
            data_index,
        })
    }
}


impl From<&QProvingJobDataID> for [u8; 24] {
    fn from(value: &QProvingJobDataID) -> Self {
        let mut result = [0u8; 24];
        result[0] = value.topic.to_u8();
        result[1..9].copy_from_slice(&value.goal_id.to_le_bytes());
        result[9] = value.circuit_type.to_u8();
        result[10..14].copy_from_slice(&value.group_id.to_le_bytes());
        result[14..18].copy_from_slice(&value.sub_group_id.to_le_bytes());
        result[18..22].copy_from_slice(&value.task_index.to_le_bytes());
        result[22] = value.data_type.to_u8();
        result[23] = value.data_index;
        result
    }
}

impl TryFrom<[u8; 24]> for QProvingJobDataID {
    type Error = anyhow::Error;
    fn try_from(value: [u8; 24]) -> Result<Self, Self::Error> {
        let topic: QJobTopic = value[0].try_into()?;
        let goal_id = u64::from_le_bytes(value[1..9].try_into()?);
        let circuit_type = ProvingJobCircuitType::try_from(value[9])?;
        let group_id = u32::from_le_bytes(value[10..14].try_into()?);
        let sub_group_id = u32::from_le_bytes(value[14..18].try_into()?);
        let task_index = u32::from_le_bytes(value[18..22].try_into()?);
        let data_type = ProvingJobDataType::try_from(value[22])?;
        let data_index = value[23];
        Ok(QProvingJobDataID {
            topic,
            goal_id,
            circuit_type,
            group_id,
            sub_group_id,
            task_index,
            data_type,
            data_index,
        })
    }
}


impl QProvingJobDataID {
    pub fn new(
        topic: QJobTopic,
        goal_id: u64,
        group_id: u32,
        sub_group_id: u32,
        task_index: u32,
        circuit_type: ProvingJobCircuitType,
        data_type: ProvingJobDataType,
        data_index: u8,
    ) -> Self {
        Self {
            topic,
            goal_id,
            circuit_type,
            group_id,
            sub_group_id,
            task_index,
            data_type,
            data_index,
        }
    }
    pub fn guta_two_end_cap_witness(checkpoint_id: u64, group_id: u32, sub_group_id: u32, task_index: u32) -> Self {
        Self::new(
            QJobTopic::GenerateStandardProof,
            checkpoint_id,
            group_id,
            sub_group_id,
            task_index,
            ProvingJobCircuitType::GUTATwoEndCap,
            ProvingJobDataType::InputWitness,
            0,
        )
    }
    pub fn guta_two_agg_witness(checkpoint_id: u64, group_id: u32, sub_group_id: u32, task_index: u32) -> Self {
        Self::new(
            QJobTopic::GenerateStandardProof,
            checkpoint_id,
            group_id,
            sub_group_id,
            task_index,
            ProvingJobCircuitType::GUTATwoGUTA,
            ProvingJobDataType::InputWitness,
            0,
        )
    }
    pub fn guta_left_end_cap_right_guta_witness(checkpoint_id: u64, group_id: u32, sub_group_id: u32, task_index: u32) -> Self {
        Self::new(
            QJobTopic::GenerateStandardProof,
            checkpoint_id,
            group_id,
            sub_group_id,
            task_index,
            ProvingJobCircuitType::GUTALeftEndCapRightGUTA,
            ProvingJobDataType::InputWitness,
            0,
        )
    }
    pub fn guta_left_guta_right_end_cap_witness(checkpoint_id: u64, group_id: u32, sub_group_id: u32, task_index: u32) -> Self {
        Self::new(
            QJobTopic::GenerateStandardProof,
            checkpoint_id,
            group_id,
            sub_group_id,
            task_index,
            ProvingJobCircuitType::GUTALeftGUTARightEndCap,
            ProvingJobDataType::InputWitness,
            0,
        )
    }
    pub fn guta_single_end_cap_witness(checkpoint_id: u64, group_id: u32, sub_group_id: u32, task_index: u32) -> Self {
        Self::new(
            QJobTopic::GenerateStandardProof,
            checkpoint_id,
            group_id,
            sub_group_id,
            task_index,
            ProvingJobCircuitType::GUTASingleEndCap,
            ProvingJobDataType::InputWitness,
            0,
        )
    }
    pub fn core_op_witness(checkpoint_id: u64, group_id: u32, circuit_type: ProvingJobCircuitType, sub_group_id: u32, task_index: u32) -> Self {
        Self::new(
            QJobTopic::GenerateStandardProof,
            checkpoint_id,
            group_id,
            sub_group_id,
            task_index,
            circuit_type,
            ProvingJobDataType::InputWitness,
            0,
        )
    }
    pub fn end_cap_proof(checkpoint_id: u64, group_id: u32, user_id: u32) -> Self {
        Self {
            topic: QJobTopic::GenerateStandardProof,
            goal_id: checkpoint_id,
            group_id,
            circuit_type: ProvingJobCircuitType::UserEndCap,
            sub_group_id: 1,
            task_index: user_id,
            data_type: ProvingJobDataType::InputProof,
            data_index: 0,
        }
    }
    pub fn get_input_proof_id(&self, data_index: u8) -> Self {
        Self {
            data_type: ProvingJobDataType::InputProof,
            data_index,
            ..*self
        }
    }


    pub fn get_output_id(&self) -> Self {
        Self {
            data_type: ProvingJobDataType::OutputProof,
            data_index: 0,
            ..*self
        }
    }
    pub fn get_input_witness_id(&self) -> Self {
        Self {
            data_type: ProvingJobDataType::InputWitness,
            data_index: 0,
            ..*self
        }
    }
    pub fn to_fixed_bytes(&self) -> [u8; 24] {
        self.into()
    }
    pub fn with_task_index(&self, task_index: u32) -> Self {
        Self { task_index, ..*self }
    }
    pub fn to_hex_string(&self) -> String {
        hex::encode(&self.to_fixed_bytes())
    }
}

