#!/usr/bin/env bash

# shellcheck source=deploy/bsc-testnet/lib.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

if [ -f "$BSC_DEPLOY_DIR/full-stack.env" ]; then
  # shellcheck disable=SC1091
  source "$BSC_DEPLOY_DIR/full-stack.env"
fi

: "${WORKSPACE_HOME:=$(cd "$PARTH_ROOT/.." && pwd)}"
: "${BSC_RUNTIME_PARTH_DIR:=$WORKSPACE_HOME/psy-node-bsc-testnet}"
: "${BSC_PSY_CONTRACTS_DIR:=$WORKSPACE_HOME/psy-contracts-bsc-testnet}"
: "${BSC_PSY_GENESIS_DIR:=$WORKSPACE_HOME/psy-genesis-bsc-testnet}"
: "${BSC_PSY_DAPP_DIR:=$WORKSPACE_HOME/psy-dapp-bsc-testnet}"
: "${PSY_SERVICES_HOME:=$WORKSPACE_HOME/psy-services-cloud-deploy}"
: "${BSC_LOCAL_BUILD:=0}"
: "${BSC_LOCAL_GENESIS_USE_LLD:=0}"
: "${BSC_LOCAL_SCYLLA_IMAGE_TAG:=2026.1.5}"
: "${BSC_LOCAL_MIN_AIO_NR:=67590}"
: "${BSC_LOCAL_REQUIRE_SCYLLA_AIO:=1}"
: "${BSC_LOCAL_REQUIRE_FREE_PORTS:=1}"
: "${BSC_RUNTIME_TARGET_DIR:=$BSC_RUNTIME_PARTH_DIR/target}"
: "${BSC_PSY_SERVICES_TARGET_DIR:=$PSY_SERVICES_HOME/target}"

: "${BSC_LOCAL_COMPOSE_PROJECT:=parth-bsc-testnet}"
: "${BSC_LOCAL_CONTAINER_PREFIX:=parth-bsc-local}"
: "${BSC_LOCAL_ENVIO_COMPOSE_PROJECT:=parth-bsc-envio}"
: "${BSC_LOCAL_ENVIO_NETWORK_NAME:=${BSC_LOCAL_ENVIO_COMPOSE_PROJECT}-network}"
: "${BSC_LOCAL_HOME:=$BSC_LOCAL_STATE_ROOT/home}"
: "${BSC_LOCAL_GROTH16_KEYSTORE_ROOT:=$BSC_LOCAL_HOME/.psy/keystore}"

: "${BSC_LOCAL_COORDINATOR_PORT:=2337}"
: "${BSC_LOCAL_REALM_BASE_PORT:=23380}"
: "${BSC_LOCAL_PROVE_PROXY_ADDR:=127.0.0.1:19999}"
: "${BSC_LOCAL_FAUCET_ADDR:=127.0.0.1:19998}"
: "${BSC_LOCAL_PSY_SERVICES_ADDR:=127.0.0.1:13000}"
: "${BSC_LOCAL_INDEXER_PORT:=28080}"
: "${BSC_LOCAL_REALM_INDEXER_START_CHECKPOINT:=0}"
: "${BSC_LOCAL_REDIS_PORT:=16379}"
: "${BSC_LOCAL_NATS_PORT:=14222}"
: "${BSC_LOCAL_SCYLLA_PORT:=19042}"
: "${BSC_LOCAL_NOSTR_PORT:=18081}"
: "${BSC_LOCAL_POSTGRES_PORT:=25432}"
: "${BSC_LOCAL_ENVIO_POSTGRES_PORT:=25433}"
: "${BSC_LOCAL_APP_PORT:=18088}"
: "${BSC_LOCAL_EXPLORER_PORT:=18089}"
: "${BSC_LOCAL_IDE_PORT:=18090}"

: "${BSC_LOCAL_RELAYER_MAX_CHECKPOINT_BATCH:=8}"
: "${BSC_LOCAL_RELAYER_CONFIRMATION_LAG_CHECKPOINTS:=1}"
: "${BSC_LOCAL_RELAYER_POLL_INTERVAL_SECS:=2}"
: "${BSC_LOCAL_START_TUNNEL:=0}"
: "${BSC_LOCAL_PUBLISH_FRONTENDS:=0}"

BSC_LOCAL_TOKEN_CONTRACT_ABI="$BSC_PSY_GENESIS_DIR/genesis_abi/USDTTokenContract.json"
if [ -z "${BSC_LOCAL_RELAYER_WITHDRAW_METHOD_ID:-}" ]; then
  [ -f "$BSC_LOCAL_TOKEN_CONTRACT_ABI" ] || die "missing file: $BSC_LOCAL_TOKEN_CONTRACT_ABI"
  require_command jq
  BSC_LOCAL_RELAYER_WITHDRAW_METHOD_ID="$(
    jq -er '.contract.methods[] | select(.name == "withdraw") | .method_id' \
      "$BSC_LOCAL_TOKEN_CONTRACT_ABI"
  )" || die "failed to read withdraw method ID from $BSC_LOCAL_TOKEN_CONTRACT_ABI"
fi

LOCAL_STAGING_SOURCE_PARTH_DIR="$BSC_RUNTIME_PARTH_DIR"
LOCAL_CF_SOURCE_PARTH_DIR="$BSC_RUNTIME_PARTH_DIR"
LOCAL_CF_LIVE_PARTH_DIR="$PARTH_ROOT"
LOCAL_STAGING_STATE_DIR="$BSC_LOCAL_STATE_ROOT"
LOCAL_STAGING_COMPOSE_PROJECT="$BSC_LOCAL_COMPOSE_PROJECT"
LOCAL_STAGING_CONTAINER_PREFIX="$BSC_LOCAL_CONTAINER_PREFIX"
LOCAL_CF_ENVIO_COMPOSE_PROJECT="$BSC_LOCAL_ENVIO_COMPOSE_PROJECT"
LOCAL_CF_ENVIO_NETWORK_NAME="$BSC_LOCAL_ENVIO_NETWORK_NAME"
LOCAL_STAGING_TARGET_DIR="$BSC_RUNTIME_TARGET_DIR"
LOCAL_STAGING_PSY_SERVICES_TARGET_DIR="$BSC_PSY_SERVICES_TARGET_DIR"
LOCAL_STAGING_GENESIS_PATH="$BSC_LOCAL_STATE_ROOT/genesis.json"
LOCAL_STAGING_PRIVATE_KEYS_PATH="$BSC_LOCAL_STATE_ROOT/private_keys.json"
LOCAL_STAGING_PSY_SERVICES_GENESIS_PATH="$BSC_PSY_GENESIS_DIR/genesis_contracts.json"
LOCAL_STAGING_PROVE_PROXY_HOME="$BSC_LOCAL_HOME"
LOCAL_GROTH16_KEYSTORE_ROOT="$BSC_LOCAL_GROTH16_KEYSTORE_ROOT"
LOCAL_STAGING_REALM_INDEXER_START_CHECKPOINT="$BSC_LOCAL_REALM_INDEXER_START_CHECKPOINT"

PSY_CONTRACTS_DIR="$BSC_PSY_CONTRACTS_DIR"
BSC_DEPLOYMENT_FILE="$BSC_PSY_CONTRACTS_DIR/deployments/bsc-testnet/deployed-contracts.json"
LOCAL_STAGING_CONTRACTS_DIR="$BSC_PSY_CONTRACTS_DIR"
LOCAL_STAGING_PSY_GENESIS_DIR="$BSC_PSY_GENESIS_DIR"
LOCAL_STAGING_PSY_DAPP_DIR="$BSC_PSY_DAPP_DIR"
LOCAL_STAGING_L1_DEPLOYMENTS_NETWORK="bsc-testnet"
LOCAL_STAGING_CHAIN_CONFIG_NETWORK="bsc-testnet"
LOCAL_STAGING_FRONTEND_NETWORK="bsc-testnet"
LOCAL_STAGING_L1_DEPLOYMENTS_JSON="$BSC_DEPLOYMENT_FILE"

LOCAL_STAGING_COORDINATOR_EDGE_PORT="$BSC_LOCAL_COORDINATOR_PORT"
LOCAL_STAGING_REALM_EDGE_BASE_PORT="$BSC_LOCAL_REALM_BASE_PORT"
LOCAL_STAGING_REALM_EDGE_PORT_STRIDE="10"
LOCAL_STAGING_PROVE_PROXY_ADDR="$BSC_LOCAL_PROVE_PROXY_ADDR"
LOCAL_STAGING_FAUCET_ADDR="$BSC_LOCAL_FAUCET_ADDR"
LOCAL_STAGING_PSY_SERVICES_ADDR="$BSC_LOCAL_PSY_SERVICES_ADDR"
LOCAL_STAGING_INDEXER_PORT="$BSC_LOCAL_INDEXER_PORT"
LOCAL_REDIS_PORT="$BSC_LOCAL_REDIS_PORT"
LOCAL_NATS_PORT="$BSC_LOCAL_NATS_PORT"
LOCAL_SCYLLA_PORT="$BSC_LOCAL_SCYLLA_PORT"
LOCAL_NOSTR_PORT="$BSC_LOCAL_NOSTR_PORT"
LOCAL_POSTGRES_PORT="$BSC_LOCAL_POSTGRES_PORT"
LOCAL_STAGING_APP_PORT="$BSC_LOCAL_APP_PORT"
LOCAL_STAGING_EXPLORER_PORT="$BSC_LOCAL_EXPLORER_PORT"
LOCAL_STAGING_IDE_PORT="$BSC_LOCAL_IDE_PORT"

LOCAL_STAGING_L1_RPC_PORT="$BSC_LOCAL_RPC_PORT"
LOCAL_STAGING_L1_RPC_URL="$BSC_LOCAL_RPC_URL"
LOCAL_STAGING_L1_CHAIN_ID="$BSC_LOCAL_CHAIN_ID"
LOCAL_STAGING_L1_BLOCK_TIME="$BSC_LOCAL_BLOCK_TIME"

LOCAL_STAGING_BUILD="$BSC_LOCAL_BUILD"
LOCAL_STAGING_GENESIS_USE_LLD="$BSC_LOCAL_GENESIS_USE_LLD"
LOCAL_SCYLLA_IMAGE_TAG="$BSC_LOCAL_SCYLLA_IMAGE_TAG"
LOCAL_STAGING_BUILD_FRONTENDS="0"
LOCAL_STAGING_PUBLISH_FRONTENDS="0"
LOCAL_STAGING_START_NGINX="0"
LOCAL_CF_STACK_PUBLISH_FRONTENDS="0"
LOCAL_CF_PUBLISH_FRONTENDS="$BSC_LOCAL_PUBLISH_FRONTENDS"
LOCAL_CF_START_TUNNEL="$BSC_LOCAL_START_TUNNEL"
LOCAL_CF_START_ANVIL="0"
LOCAL_CF_DEPLOY_L1_CONTRACTS="1"
LOCAL_CF_START_ETH_FAUCET="0"
LOCAL_CF_START_ENVIO="1"
LOCAL_CF_RESET_ENVIO_ON_START="${BSC_LOCAL_RESET_ENVIO_ON_START:-1}"
LOCAL_CF_ENVIO_START_BLOCK="1"
LOCAL_CF_ENVIO_PG_PORT="$BSC_LOCAL_ENVIO_POSTGRES_PORT"
LOCAL_CF_START_RELAYER="1"

LOCAL_STAGING_RELAYER_MAX_CHECKPOINT_BATCH="$BSC_LOCAL_RELAYER_MAX_CHECKPOINT_BATCH"
LOCAL_STAGING_RELAYER_CONFIRMATION_LAG_CHECKPOINTS="$BSC_LOCAL_RELAYER_CONFIRMATION_LAG_CHECKPOINTS"
LOCAL_STAGING_RELAYER_POLL_INTERVAL_SECS="$BSC_LOCAL_RELAYER_POLL_INTERVAL_SECS"
LOCAL_STAGING_RELAYER_WITHDRAW_METHOD_ID="$BSC_LOCAL_RELAYER_WITHDRAW_METHOD_ID"
LOCAL_STAGING_RELAYER_L1_PRIVATE_KEY="$BSC_LOCAL_DEPLOY_PRIVATE_KEY"
LOCAL_STAGING_RELAYER_CONFIG="$BSC_LOCAL_STATE_ROOT/bridge-relayer.toml"
LOCAL_STAGING_RELAYER_PROOF_DIR="$BSC_LOCAL_STATE_ROOT/bridge-relayer"
LOCAL_STAGING_RELAYER_RPC_CONFIG="$BSC_LOCAL_STATE_ROOT/bridge-relayer-client_prover-config.json"
LOCAL_STAGING_PSY_FAUCET_TEMPLATE_JSON_PATH="$BSC_LOCAL_STATE_ROOT/faucetOperators.template.json"
LOCAL_STAGING_PSY_FAUCET_GENERATED_OPERATORS_JSON_PATH="$BSC_LOCAL_STATE_ROOT/faucetOperators.json"

LOCAL_CF_STATE_DIR="$BSC_LOCAL_STATE_ROOT/cloudflare"
LOCAL_CF_BACKEND_ABI_SNAPSHOT_ROOT="$BSC_LOCAL_STATE_ROOT/backend-abi"
LOCAL_CF_CHAIN_CONFIG_FILE="$BSC_LOCAL_STATE_ROOT/client_prover/public-config.json"
LOCAL_CF_ORIGINAL_CHAIN_CONFIG="$BSC_PSY_GENESIS_DIR/config.json"
LOCAL_STAGING_RPC_CONFIG="$BSC_LOCAL_STATE_ROOT/client_prover/config.json"

bsc_full_stack_export() {
  export WORKSPACE_HOME BSC_RUNTIME_PARTH_DIR BSC_PSY_CONTRACTS_DIR BSC_PSY_GENESIS_DIR BSC_PSY_DAPP_DIR PSY_SERVICES_HOME
  export BSC_RUNTIME_TARGET_DIR BSC_PSY_SERVICES_TARGET_DIR LOCAL_STAGING_TARGET_DIR LOCAL_STAGING_PSY_SERVICES_TARGET_DIR
  export LOCAL_STAGING_GENESIS_PATH LOCAL_STAGING_PRIVATE_KEYS_PATH
  export LOCAL_STAGING_PSY_SERVICES_GENESIS_PATH
  export BSC_LOCAL_HOME BSC_LOCAL_GROTH16_KEYSTORE_ROOT
  export LOCAL_STAGING_PROVE_PROXY_HOME LOCAL_GROTH16_KEYSTORE_ROOT
  export BSC_LOCAL_REALM_INDEXER_START_CHECKPOINT LOCAL_STAGING_REALM_INDEXER_START_CHECKPOINT
  export BSC_LOCAL_STATE_ROOT PSY_CONTRACTS_DIR BSC_DEPLOYMENT_FILE BSC_LOCAL_RPC_PORT BSC_LOCAL_RPC_URL BSC_LOCAL_CHAIN_ID BSC_LOCAL_BLOCK_TIME
  export LOCAL_STAGING_SOURCE_PARTH_DIR LOCAL_CF_SOURCE_PARTH_DIR LOCAL_CF_LIVE_PARTH_DIR LOCAL_STAGING_STATE_DIR
  export LOCAL_STAGING_COMPOSE_PROJECT LOCAL_STAGING_CONTAINER_PREFIX LOCAL_CF_ENVIO_COMPOSE_PROJECT LOCAL_CF_ENVIO_NETWORK_NAME
  export LOCAL_STAGING_CONTRACTS_DIR LOCAL_STAGING_PSY_GENESIS_DIR LOCAL_STAGING_PSY_DAPP_DIR
  export LOCAL_STAGING_L1_DEPLOYMENTS_NETWORK LOCAL_STAGING_CHAIN_CONFIG_NETWORK LOCAL_STAGING_FRONTEND_NETWORK
  export LOCAL_STAGING_L1_DEPLOYMENTS_JSON LOCAL_STAGING_COORDINATOR_EDGE_PORT LOCAL_STAGING_REALM_EDGE_BASE_PORT
  export LOCAL_STAGING_REALM_EDGE_PORT_STRIDE LOCAL_STAGING_PROVE_PROXY_ADDR LOCAL_STAGING_FAUCET_ADDR
  export LOCAL_STAGING_PSY_SERVICES_ADDR LOCAL_STAGING_INDEXER_PORT LOCAL_REDIS_PORT LOCAL_NATS_PORT
  export LOCAL_SCYLLA_PORT LOCAL_NOSTR_PORT LOCAL_POSTGRES_PORT LOCAL_STAGING_APP_PORT
  export LOCAL_STAGING_EXPLORER_PORT LOCAL_STAGING_IDE_PORT LOCAL_STAGING_L1_RPC_PORT
  export LOCAL_STAGING_L1_RPC_URL LOCAL_STAGING_L1_CHAIN_ID LOCAL_STAGING_L1_BLOCK_TIME
  export LOCAL_STAGING_BUILD LOCAL_STAGING_GENESIS_USE_LLD LOCAL_SCYLLA_IMAGE_TAG
  export LOCAL_STAGING_BUILD_FRONTENDS
  export LOCAL_STAGING_PUBLISH_FRONTENDS LOCAL_STAGING_START_NGINX
  export LOCAL_CF_STACK_PUBLISH_FRONTENDS LOCAL_CF_PUBLISH_FRONTENDS LOCAL_CF_START_TUNNEL LOCAL_CF_START_ANVIL
  export LOCAL_CF_DEPLOY_L1_CONTRACTS LOCAL_CF_START_ETH_FAUCET LOCAL_CF_START_ENVIO
  export LOCAL_CF_RESET_ENVIO_ON_START LOCAL_CF_ENVIO_START_BLOCK LOCAL_CF_ENVIO_PG_PORT LOCAL_CF_START_RELAYER
  export LOCAL_STAGING_RELAYER_MAX_CHECKPOINT_BATCH LOCAL_STAGING_RELAYER_CONFIRMATION_LAG_CHECKPOINTS
  export BSC_LOCAL_TOKEN_CONTRACT_ABI BSC_LOCAL_RELAYER_WITHDRAW_METHOD_ID
  export LOCAL_STAGING_RELAYER_POLL_INTERVAL_SECS LOCAL_STAGING_RELAYER_WITHDRAW_METHOD_ID
  export LOCAL_STAGING_RELAYER_L1_PRIVATE_KEY
  export LOCAL_STAGING_RELAYER_CONFIG LOCAL_STAGING_RELAYER_PROOF_DIR LOCAL_STAGING_RELAYER_RPC_CONFIG
  export LOCAL_STAGING_PSY_FAUCET_TEMPLATE_JSON_PATH LOCAL_STAGING_PSY_FAUCET_GENERATED_OPERATORS_JSON_PATH
  export LOCAL_CF_STATE_DIR LOCAL_CF_BACKEND_ABI_SNAPSHOT_ROOT LOCAL_CF_CHAIN_CONFIG_FILE
  export LOCAL_CF_ORIGINAL_CHAIN_CONFIG LOCAL_STAGING_RPC_CONFIG
}
