[package]
edition = "2021"
name    = "psy_io"
version = "0.1.0"

[features]
default = ["std", "tokio_helper"]
std = ["alloc", "embedded-io/std", "embedded-io-async/std"]
alloc = ["embedded-io/alloc", "embedded-io-async/std"]
tokio_helper = ["dep:tokio", "dep:async-trait"]

[dependencies]
anyhow     = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
embedded-io = { workspace = true }
embedded-io-async = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, optional = true, features = ["fs"] }
async-trait = { workspace = true, optional = true }
