[package]
edition = "2021"
name    = "psy_io"
version = "0.1.0"

[features]
default = ["std", "tokio_helper"]
std = ["alloc", "embedded-io/std", "embedded-io-async/std"]
alloc = ["embedded-io/alloc", "embedded-io-async/std"]
tokio_helper = ["dep:tokio", "dep:async-trait"]

[dependencies]
anyhow     = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
embedded-io = { workspace = true }
embedded-io-async = { workspace = true }
tokio = { workspace = true, optional = true }
async-trait = { workspace = true, optional = true }