// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DapenCFCProvingSessionStartContext } from "./DapenCFCProvingSessionStartContext";
import type { DapenCFCUserTransactionCallStartContext } from "./DapenCFCUserTransactionCallStartContext";
import type { DapenCFCUserTransactionEndContext } from "./DapenCFCUserTransactionEndContext";

export type DapenCFCUserTransactionInputContext = { proving_session_start_ctx: DapenCFCProvingSessionStartContext, transaction_call_start_ctx: DapenCFCUserTransactionCallStartContext, transaction_end_ctx: DapenCFCUserTransactionEndContext, };
