// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MerkleProofCore } from "./MerkleProofCore";
import type { PsyCheckpointGlobalStateRoots } from "./PsyCheckpointGlobalStateRoots";
import type { PsyCheckpointLeafStats } from "./PsyCheckpointLeafStats";
import type { QHashOut } from "./QHashOut";

export type DPNCheckpointGlobalStateRootsWitness = { checkpoint_state_roots: PsyCheckpointGlobalStateRoots, checkpoint_leaf_stats: PsyCheckpointLeafStats, checkpoint_historical_proof: MerkleProofCore<QHashOut>, };
