// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeltaMerkleProofCore } from "./DeltaMerkleProofCore";
import type { IMTContractStateLeaf } from "./IMTContractStateLeaf";

export type DPNIMTSetWitness = { delta_merkle_proofs: Array<DeltaMerkleProofCore>, is_insert: boolean, insert_has_predecessor: boolean, old_leaf: IMTContractStateLeaf, new_leaf: IMTContractStateLeaf, predecessor_old_leaf: IMTContractStateLeaf, predecessor_new_leaf: IMTContractStateLeaf, };
