// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DPNReadOtherUserLeafMerkleProof } from "./DPNReadOtherUserLeafMerkleProof";
import type { IMTContractStateLeaf } from "./IMTContractStateLeaf";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QHashOut } from "./QHashOut";

export type DPNIMTContainsOtherUserWitness = { exists: boolean, user_leaf_witness: DPNReadOtherUserLeafMerkleProof, contract_state_proof: MerkleProofCore<QHashOut>, state_slot_proof: MerkleProofCore<QHashOut>, leaf_preimage: IMTContractStateLeaf, };
