// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IMTContractStateLeaf } from "./IMTContractStateLeaf";
import type { MerkleProofCore } from "./MerkleProofCore";
import type { QHashOut } from "./QHashOut";

export type DPNIMTContainsWitness = { exists: boolean, leaf_preimage: IMTContractStateLeaf, merkle_proof: MerkleProofCore<QHashOut>, };
