// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type DPNProvingSessionCompactMethodCall = { caller_contract_id: bigint, contract_id: bigint, method_id: bigint, inputs_length: bigint, inputs_hash: QHashOut, };
