// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MerkleProofCore } from "./MerkleProofCore";
import type { PsyUserLeaf } from "./PsyUserLeaf";
import type { QHashOut } from "./QHashOut";

export type DPNReadOtherUserLeafMerkleProof = { user_tree_proof: MerkleProofCore<QHashOut>, user_leaf: PsyUserLeaf, };
