// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Check if an IMT key exists (other user, external contract).
 */
export type DPNStateCmdContainsOtherUserIMTContractStateValue = { user_id: bigint, contract_id: bigint, base_offset: bigint, capacity: bigint, key: [bigint, bigint, bigint, bigint], contract_state_tree_height: number, };
