// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Set an IMT contract state value by 256-bit key.
 * key[4] = the 256-bit storage key, value[4] = the new 256-bit value.
 */
export type DPNStateCmdSetIMTContractStateValue = { condition: bigint, base_offset: bigint, capacity: bigint, key: [bigint, bigint, bigint, bigint], value: [bigint, bigint, bigint, bigint], };
