// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DapenContractFunctionCircuitInput } from "./DapenContractFunctionCircuitInput";
import type { PsyUserLeaf } from "./PsyUserLeaf";
import type { PsyUserProvingSessionSignatureDataCompact } from "./PsyUserProvingSessionSignatureDataCompact";
import type { SignContext } from "./SignContext";

export type DPNSoftwareDefinedSignatureInput = { cfc_input: DapenContractFunctionCircuitInput, sig_data: PsyUserProvingSessionSignatureDataCompact, sign_context: SignContext, start_session_user_leaf: PsyUserLeaf, nonce: bigint, };
