// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Check if an IMT key exists (self user, current contract).
 */
export type DPNStateCmdContainsSelfUserCurrentIMTContractStateValue = { base_offset: bigint, capacity: bigint, key: [bigint, bigint, bigint, bigint], };
