// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

/**
 * Leaf preimage for an Indexed Merkle Tree (IMT) leaf in a contract state
 * tree.
 *
 * Each leaf in an IMT stores:
 * - `key`: the 256-bit storage key (e.g., nullifier hash, mapping key)
 * - `value`: the 256-bit storage value
 * - `next_key`: the key of the successor leaf in sorted order (zero = no
 *   successor)
 * - `next_index`: the leaf index of the successor in the tree (zero = no
 *   successor)
 *
 * The leaf hash is computed from all 13 field elements via Poseidon hashing.
 * Index 0 is always the sentinel leaf with all fields set to zero.
 *
 * This structure matches the chain-side `IMTContractStateLeaf` defined in
 * `psy_client_data/src/v1/qdata/contract/imt_leaf.rs` in the node codebase.
 */
export type IMTContractStateLeaf = { 
/**
 * 256-bit storage key (4 field elements)
 */
key: QHashOut, 
/**
 * 256-bit storage value (4 field elements)
 */
value: QHashOut, 
/**
 * Key of the successor leaf in sorted order (zero = end of list)
 */
next_key: QHashOut, 
/**
 * Leaf index of the successor (zero = end of list)
 */
next_index: bigint, };
