// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type PsyContractLeaf = { deployer: QHashOut, function_tree_root: QHashOut, code_root: QHashOut, state_tree_height: bigint, state_layout_root: QHashOut, state_layout_field_count: bigint, state_layout_slot_count: bigint, };
