// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DPNStateCmd } from "./DPNStateCmd";
import type { DPNStateCmdWitness } from "./DPNStateCmdWitness";

export type PsyCmdWithInputAndWitness = { state_cmd: DPNStateCmd, witness: DPNStateCmdWitness, result: Array<bigint>, };
