// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QHashOut } from "./QHashOut";

export type PsyUserProvingSessionSignatureDataCompact = { start_user_leaf_hash: QHashOut, end_user_leaf_hash: QHashOut, checkpoint_leaf_hash: QHashOut, tx_stack_hash: QHashOut, tx_count: bigint, };
