// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PsyUserEventRecord = { checkpoint_id: bigint, user_id: bigint, contract_id: bigint, method_id: bigint, event_index: bigint, data: Array<bigint>, };
