#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PARTH_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONFIG_FILE="${GCP_DEPLOY_CONFIG:-$PARTH_DIR/deploy/gcp/config.env}"
OUT_DIR="${LOCAL_PROVE_PROXY_DIR:-$PARTH_DIR/dist/local-prove-proxy}"

[ -f "$CONFIG_FILE" ] || {
  echo "missing config file: $CONFIG_FILE" >&2
  exit 1
}

set -a
# shellcheck source=../gcp/config.env
source "$CONFIG_FILE"
set +a

require_var() {
  local name="$1"
  if [ -z "${!name:-}" ]; then
    echo "missing required config variable: $name" >&2
    exit 1
  fi
}

require_var PUBLIC_COORDINATOR_DOMAIN
require_var PUBLIC_PSY_SERVICES_DOMAIN

realm0_domain="${PUBLIC_REALM0_DOMAIN:-${PUBLIC_REALM_DOMAIN:-}}"
realm1_domain="${PUBLIC_REALM1_DOMAIN:-}"
[ -n "$realm0_domain" ] || {
  echo "missing PUBLIC_REALM0_DOMAIN or PUBLIC_REALM_DOMAIN" >&2
  exit 1
}

prove_proxy_bin="$PARTH_DIR/target/release/psy_user_cli"
[ -x "$prove_proxy_bin" ] || {
  echo "missing prove proxy binary: $prove_proxy_bin" >&2
  echo "build it first: cargo build --release --bin psy_user_cli" >&2
  exit 1
}

source_config="$PARTH_DIR/deploy/config/parth/client_prover_config.json"
[ -f "$source_config" ] || {
  echo "missing client prover config template: $source_config" >&2
  exit 1
}

mkdir -p "$OUT_DIR/bin" "$OUT_DIR/client_prover" "$OUT_DIR/logs"
tmp_bin="$OUT_DIR/bin/psy_user_cli.tmp.$$"
cp "$prove_proxy_bin" "$tmp_bin"
chmod 0755 "$tmp_bin"
mv -f "$tmp_bin" "$OUT_DIR/bin/psy_user_cli"

realm_urls="https://$realm0_domain"
if [ -n "$realm1_domain" ]; then
  realm_urls="$realm_urls,https://$realm1_domain"
fi

python3 - "$source_config" "$OUT_DIR/client_prover/config.json" \
  "https://$PUBLIC_COORDINATOR_DOMAIN" \
  "$realm_urls" \
  "http://127.0.0.1:${LOCAL_PROVE_PROXY_PORT:-9999}" \
  "https://$PUBLIC_PSY_SERVICES_DOMAIN" <<'PY'
import json
import sys

source, target, coordinator, realms_csv, prove_proxy, services = sys.argv[1:]
with open(source, "r", encoding="utf-8") as f:
    data = json.load(f)

localhost = data.setdefault("networks", {}).setdefault("localhost", {})
localhost["coordinator_configs"] = [{"id": 0, "rpc_url": [coordinator]}]
localhost["realm_configs"] = [
    {"id": idx, "rpc_url": [url.strip()]}
    for idx, url in enumerate(realms_csv.split(","))
    if url.strip()
]
localhost["prove_proxy_url"] = [prove_proxy]
localhost["api_services_url"] = [services]

with open(target, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2)
    f.write("\n")
PY

cat > "$OUT_DIR/run.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

export RUST_LOG="${RUST_LOG:-info}"

exec "$PWD/bin/psy_user_cli" prove-proxy \
  --listen-addr "${LOCAL_PROVE_PROXY_LISTEN_ADDR:-127.0.0.1:9999}" \
  --rpc-config "$PWD/client_prover/config.json"
EOF
chmod 0755 "$OUT_DIR/run.sh"

cat > "$OUT_DIR/env.example" <<'EOF'
# Do not commit this file.
RUST_LOG=info
LOCAL_PROVE_PROXY_LISTEN_ADDR=127.0.0.1:9999
EOF

cat > "$OUT_DIR/README.md" <<EOF
# Local Prove Proxy

Generated by \`deploy/local-prove-proxy/prepare-local-prove-proxy.sh\`.

Run manually:

\`\`\`bash
cd "$OUT_DIR"
./run.sh
\`\`\`

Install as a user service:

\`\`\`bash
bash "$PARTH_DIR/deploy/local-prove-proxy/install-systemd-user-service.sh"
systemctl --user start parth-local-prove-proxy.service
journalctl --user -u parth-local-prove-proxy.service -f
\`\`\`

Install Groth16 setup files locally before serving withdrawal claims:

\`\`\`bash
bash "$PARTH_DIR/deploy/local-relayer/install-local-groth16-setup.sh"
\`\`\`
EOF

echo "prepared local prove proxy runtime: $OUT_DIR"
echo "run it with:"
echo "  cd $OUT_DIR"
echo "  ./run.sh"
