[package]
name = "sp1-plonky2-program"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }
plonky2 = { workspace = true }
sp1-plonky2-lib = { path = "../lib" }
tiny-keccak = { workspace = true, features = ["keccak"] }

