#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/lib/common.sh"

NAME="${NOSTR_VM_NAME:-parth-nostr-1}"
NODE_HOST="${NODE_HOST:-$(instance_internal_dns "${NODE_VM_NAME:-gcp-cp-ce}")}"
PROVE_PROXY_HOST="${PROVE_PROXY_HOST:-$(instance_internal_dns "${PROVE_PROXY_VM_NAME:-gcp-prove-proxy}")}"
FAUCET_HOST="${FAUCET_HOST:-$(instance_internal_dns "${FAUCET_VM_NAME:-${PROVE_PROXY_VM_NAME:-gcp-prove-proxy}}")}"
ANVIL_VM_NAME="${ANVIL_VM_NAME:-${NODE_VM_NAME:-gcp-cp-ce}}"
ANVIL_HOST="${ANVIL_HOST:-$(instance_internal_dns "$ANVIL_VM_NAME")}"
POSTGRES_HOST="${POSTGRES_HOST:-$(instance_internal_dns "${POSTGRES_VM_NAME:-gcp-postgres}")}"
if [ "${L1_DEPLOYMENTS_NETWORK:-localhost}" != "localhost" ] || [ "${CHAIN_ID:-31337}" != "31337" ]; then
  DEFAULT_PUBLIC_L1_RPC_UPSTREAM="${ETH_RPC_URL:-}"
else
  DEFAULT_PUBLIC_L1_RPC_UPSTREAM="${ANVIL_HOST}:${ANVIL_PORT:-8545}"
fi
provision_vm "$NAME"
run_remote_script "$NAME" "$GCP_DIR/remote/prepare-parth-host.sh"
run_remote_script "$NAME" "$GCP_DIR/remote/install-nostr.sh" \
  "DATA_DISK_DEVICE=${NOSTR_DATA_DISK_DEVICE:-}" \
  "DATA_DISK_MOUNTPOINT=${NOSTR_HOME:-/opt/nostr-relay}" \
  "NOSTR_HOME=${NOSTR_HOME:-/opt/nostr-relay}" \
  "NOSTR_RELAY_IMAGE=${NOSTR_RELAY_IMAGE:-scsibug/nostr-rs-relay:latest}" \
  "NOSTR_RELAY_URL=${NOSTR_RELAY_URL}" \
  "NOSTR_DOMAIN=${NOSTR_DOMAIN}" \
  "NOSTR_ALIAS_DOMAINS=${NOSTR_ALIAS_DOMAINS:-}" \
  "NOSTR_NAME=${NOSTR_NAME:-psy-protocol-nostr-stg}" \
  "NOSTR_DESCRIPTION=${NOSTR_DESCRIPTION:-Psy Protocol staging Nostr relay for bridge infrastructure}" \
  "NOSTR_CONTACT=${NOSTR_CONTACT:-tyree@zklabs.cn}" \
  "NOSTR_PUBKEY=${NOSTR_PUBKEY:-}" \
  "NOSTR_INTERNAL_PORT=${NOSTR_INTERNAL_PORT:-8080}" \
  "NOSTR_DB_MIN_CONN=${NOSTR_DB_MIN_CONN:-4}" \
  "NOSTR_DB_MAX_CONN=${NOSTR_DB_MAX_CONN:-16}" \
  "NOSTR_MAX_EVENT_BYTES=${NOSTR_MAX_EVENT_BYTES:-5242880}" \
  "NOSTR_MESSAGES_PER_SEC=${NOSTR_MESSAGES_PER_SEC:-20}" \
  "NOSTR_SUBSCRIPTIONS_PER_MIN=${NOSTR_SUBSCRIPTIONS_PER_MIN:-200}" \
  "NOSTR_MAX_BLOCKING_THREADS=${NOSTR_MAX_BLOCKING_THREADS:-16}" \
  "NOSTR_EVENT_KIND_ALLOWLIST=${NOSTR_EVENT_KIND_ALLOWLIST:-[1059]}" \
  "NOSTR_REJECT_FUTURE_SECONDS=${NOSTR_REJECT_FUTURE_SECONDS:-1800}" \
  "NOSTR_MAINTENANCE_ENABLED=${NOSTR_MAINTENANCE_ENABLED:-1}" \
  "NOSTR_MAINTENANCE_ONCALENDAR=${NOSTR_MAINTENANCE_ONCALENDAR:-*-*-* 03:00:00 Asia/Singapore}" \
  "NOSTR_DISK_FREE_TARGET_PERCENT=${NOSTR_DISK_FREE_TARGET_PERCENT:-30}" \
  "NOSTR_RETENTION_WINDOWS_DAYS=${NOSTR_RETENTION_WINDOWS_DAYS:-30 15 7 3 1}" \
  "NOSTR_SQLITE_BUSY_TIMEOUT_MS=${NOSTR_SQLITE_BUSY_TIMEOUT_MS:-30000}" \
  "NOSTR_DB_PATH=${NOSTR_DB_PATH:-}" \
  "PUBLIC_COORDINATOR_DOMAIN=${PUBLIC_COORDINATOR_DOMAIN:-}" \
  "PUBLIC_COORDINATOR_ALIAS_DOMAINS=${PUBLIC_COORDINATOR_ALIAS_DOMAINS:-}" \
  "PUBLIC_COORDINATOR_UPSTREAM=${PUBLIC_COORDINATOR_UPSTREAM:-${NODE_HOST}:${COORDINATOR_EDGE_PORT:-1337}}" \
  "PUBLIC_REALM_DOMAIN=${PUBLIC_REALM_DOMAIN:-}" \
  "PUBLIC_REALM_ALIAS_DOMAINS=${PUBLIC_REALM_ALIAS_DOMAINS:-}" \
  "PUBLIC_REALM_UPSTREAM=${PUBLIC_REALM_UPSTREAM:-${NODE_HOST}:${REALM0_EDGE_PORT:-${REALM_EDGE_PORT:-1338}}}" \
  "PUBLIC_REALM1_DOMAIN=${PUBLIC_REALM1_DOMAIN:-}" \
  "PUBLIC_REALM1_ALIAS_DOMAINS=${PUBLIC_REALM1_ALIAS_DOMAINS:-}" \
  "PUBLIC_REALM1_UPSTREAM=${PUBLIC_REALM1_UPSTREAM:-${NODE_HOST}:${REALM1_EDGE_PORT:-1339}}" \
  "PUBLIC_PROVE_PROXY_DOMAIN=${PUBLIC_PROVE_PROXY_DOMAIN:-}" \
  "PUBLIC_PROVE_PROXY_ALIAS_DOMAINS=${PUBLIC_PROVE_PROXY_ALIAS_DOMAINS:-}" \
  "PUBLIC_PROVE_PROXY_UPSTREAM=${PUBLIC_PROVE_PROXY_UPSTREAM:-${PROVE_PROXY_HOST}:9999}" \
  "PUBLIC_FAUCET_DOMAIN=${PUBLIC_FAUCET_DOMAIN:-}" \
  "PUBLIC_FAUCET_ALIAS_DOMAINS=${PUBLIC_FAUCET_ALIAS_DOMAINS:-}" \
  "PUBLIC_FAUCET_UPSTREAM=${PUBLIC_FAUCET_UPSTREAM:-${FAUCET_HOST}:9998}" \
  "PUBLIC_L1_RPC_DOMAIN=${PUBLIC_L1_RPC_DOMAIN:-}" \
  "PUBLIC_L1_RPC_ALIAS_DOMAINS=${PUBLIC_L1_RPC_ALIAS_DOMAINS:-}" \
  "PUBLIC_L1_RPC_UPSTREAM=${PUBLIC_L1_RPC_UPSTREAM:-$DEFAULT_PUBLIC_L1_RPC_UPSTREAM}" \
  "PUBLIC_PSY_SERVICES_DOMAIN=${PUBLIC_PSY_SERVICES_DOMAIN:-}" \
  "PUBLIC_PSY_SERVICES_ALIAS_DOMAINS=${PUBLIC_PSY_SERVICES_ALIAS_DOMAINS:-}" \
  "PUBLIC_PSY_SERVICES_UPSTREAM=${PUBLIC_PSY_SERVICES_UPSTREAM:-${NODE_HOST}:${PSY_SERVICES_PORT:-3000}}" \
  "PUBLIC_INDEXER_DOMAIN=${PUBLIC_INDEXER_DOMAIN:-}" \
  "PUBLIC_INDEXER_ALIAS_DOMAINS=${PUBLIC_INDEXER_ALIAS_DOMAINS:-}" \
  "PUBLIC_INDEXER_UPSTREAM=${PUBLIC_INDEXER_UPSTREAM:-${POSTGRES_HOST}:${HASURA_EXTERNAL_PORT:-18080}}" \
  "PUBLIC_TRUST_SETUP_PATH=${PUBLIC_TRUST_SETUP_PATH:-/trust-setup}" \
  "PUBLIC_TRUST_SETUP_ROOT=${PUBLIC_TRUST_SETUP_ROOT:-${NOSTR_HOME:-/opt/nostr-relay}/public/trust-setup}"

# install-nostr bootstraps the containers. Render the authoritative Caddyfile
# through the shared entrypoint script so canonical and alias domains stay in
# sync for both standalone and full-stack Nostr deployments.
bash "$GCP_DIR/deploy-caddy-entrypoints.sh"

run_health_check "$NAME" "nostr" \
  "NOSTR_HTTP_PORT=${NOSTR_HTTP_PORT:-80}" \
  "NOSTR_HTTPS_PORT=${NOSTR_HTTPS_PORT:-443}" \
  "NOSTR_INTERNAL_PORT=${NOSTR_INTERNAL_PORT:-8080}" \
  "NOSTR_MAINTENANCE_ENABLED=${NOSTR_MAINTENANCE_ENABLED:-1}" \
  "HEALTHCHECK_START_DELAY=${NOSTR_HEALTHCHECK_START_DELAY:-10}"
