#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/lib/common.sh"

if [ -z "${ENVIO_VM_NAME:-}" ]; then
  echo "ENVIO_VM_NAME must be set before deploying Envio" >&2
  exit 1
fi

NAME="$ENVIO_VM_NAME"
POSTGRES_HOST="${POSTGRES_HOST:-$(instance_internal_dns "${POSTGRES_VM_NAME:-gcp-postgres}")}"
ANVIL_VM_NAME="${ANVIL_VM_NAME:-${NODE_VM_NAME:-gcp-cp-ce}}"
ANVIL_HOST="${ANVIL_HOST:-$(instance_internal_dns "$ANVIL_VM_NAME")}"
ANVIL_PORT="${ANVIL_PORT:-8545}"
ETH_RPC_URL="${ETH_RPC_URL:-http://${ANVIL_HOST}:${ANVIL_PORT}}"
ENVIO_PG_HOST="${ENVIO_PG_HOST:-$POSTGRES_HOST}"
ENVIO_PG_PORT="${ENVIO_PG_PORT:-5432}"
ENVIO_DATABASE_URL="${ENVIO_DATABASE_URL:-$(postgres_url "$ENVIO_PG_HOST" "$ENVIO_PG_PORT" "${ENVIO_PG_DATABASE:-envio_bridge}" "${ENVIO_PG_USER:-${POSTGRES_USER:-postgres}}" "${ENVIO_PG_PASSWORD:-${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be set for shared Envio Postgres}}")}"

provision_vm "$NAME"

if [ -z "${ENVIO_BUNDLE:-}" ]; then
  ENVIO_BUNDLE="$(bash "$GCP_DIR/build-envio-bundle.sh")"
fi

upload_envio_bundle "$NAME" "$ENVIO_BUNDLE"
run_remote_script "$NAME" "$GCP_DIR/remote/install-envio.sh" \
  "ETH_RPC_URL=${ETH_RPC_URL:-}" \
  "CHAIN_ID=${CHAIN_ID:-31337}" \
  "START_BLOCK=${START_BLOCK:-1}" \
  "ENVIO_USE_HYPERSYNC=${ENVIO_USE_HYPERSYNC:-auto}" \
  "ENVIO_HYPERSYNC_URL=${ENVIO_HYPERSYNC_URL:-}" \
  "ENVIO_CONFIRMED_BLOCK_THRESHOLD=${ENVIO_CONFIRMED_BLOCK_THRESHOLD:-8}" \
  "ENVIO_RPC_POLLING_INTERVAL_MILLIS=${ENVIO_RPC_POLLING_INTERVAL_MILLIS:-}" \
  "ENVIO_RPC_INITIAL_BLOCK_INTERVAL=${ENVIO_RPC_INITIAL_BLOCK_INTERVAL:-50000}" \
  "ENVIO_RPC_BACKOFF_MULTIPLICATIVE=${ENVIO_RPC_BACKOFF_MULTIPLICATIVE:-0.8}" \
  "ENVIO_RPC_ACCELERATION_ADDITIVE=${ENVIO_RPC_ACCELERATION_ADDITIVE:-10000}" \
  "ENVIO_RPC_INTERVAL_CEILING=${ENVIO_RPC_INTERVAL_CEILING:-100000}" \
  "ENVIO_RPC_BACKOFF_MILLIS=${ENVIO_RPC_BACKOFF_MILLIS:-5000}" \
  "ENVIO_RPC_QUERY_TIMEOUT_MILLIS=${ENVIO_RPC_QUERY_TIMEOUT_MILLIS:-20000}" \
  "ENVIO_RPC_FALLBACK_STALL_TIMEOUT_MILLIS=${ENVIO_RPC_FALLBACK_STALL_TIMEOUT_MILLIS:-10000}" \
  "ENVIO_RPC_METERING=${ENVIO_RPC_METERING:-1}" \
  "ENVIO_RPC_HEIGHT_LOG_EVERY=${ENVIO_RPC_HEIGHT_LOG_EVERY:-300}" \
  "ENVIO_RPC_GET_LOGS_LOG_EVERY=${ENVIO_RPC_GET_LOGS_LOG_EVERY:-100}" \
  "BRIDGE_ADDRESS=${BRIDGE_ADDRESS:-}" \
  "STATE_MANAGER_ADDRESS=${STATE_MANAGER_ADDRESS:-}" \
  "ENVIO_DATABASE_URL=$ENVIO_DATABASE_URL" \
  "ENVIO_PG_HOST=$ENVIO_PG_HOST" \
  "ENVIO_PG_PORT=$ENVIO_PG_PORT" \
  "ENVIO_GENERATED_PG_PORT=${ENVIO_GENERATED_PG_PORT:-15432}" \
  "HASURA_EXTERNAL_PORT=${HASURA_EXTERNAL_PORT:-18080}" \
  "HASURA_INTERNAL_PORT=${HASURA_INTERNAL_PORT:-8080}" \
  "ENVIO_PG_USER=${ENVIO_PG_USER:-postgres}" \
  "ENVIO_PG_PASSWORD=${ENVIO_PG_PASSWORD:-${POSTGRES_PASSWORD:-testing}}" \
  "ENVIO_PG_DATABASE=${ENVIO_PG_DATABASE:-envio_bridge}" \
  "ENVIO_PG_PUBLIC_SCHEMA=${ENVIO_PG_PUBLIC_SCHEMA:-envio}" \
  "HASURA_GRAPHQL_ADMIN_SECRET=${HASURA_GRAPHQL_ADMIN_SECRET:-testing}"
run_health_check "$NAME" "envio" \
  "HEALTHCHECK_ATTEMPTS=${ENVIO_HEALTHCHECK_ATTEMPTS:-90}" \
  "HEALTHCHECK_DELAY=${ENVIO_HEALTHCHECK_DELAY:-3}" \
  "HEALTHCHECK_START_DELAY=${ENVIO_HEALTHCHECK_START_DELAY:-10}" \
  "ENVIO_DATABASE_URL=$ENVIO_DATABASE_URL" \
  "ENVIO_PG_HOST=$ENVIO_PG_HOST" \
  "ENVIO_PG_PORT=$ENVIO_PG_PORT" \
  "HASURA_EXTERNAL_PORT=${HASURA_EXTERNAL_PORT:-18080}" \
  "HASURA_INTERNAL_PORT=${HASURA_INTERNAL_PORT:-8080}" \
  "ENVIO_PG_USER=${ENVIO_PG_USER:-postgres}" \
  "ENVIO_PG_PASSWORD=${ENVIO_PG_PASSWORD:-${POSTGRES_PASSWORD:-testing}}" \
  "ENVIO_PG_DATABASE=${ENVIO_PG_DATABASE:-envio_bridge}" \
  "ENVIO_PG_PUBLIC_SCHEMA=${ENVIO_PG_PUBLIC_SCHEMA:-envio}"
