#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/lib/common.sh"

NAME="${NOSTR_VM_NAME:-gcp-nostr}"
NODE_HOST="${NODE_HOST:-$(instance_internal_dns "${NODE_VM_NAME:-gcp-cp-ce}")}"
PROVE_PROXY_HOST="${PROVE_PROXY_HOST:-$(instance_internal_dns "${PROVE_PROXY_VM_NAME:-gcp-prove-proxy}")}"
FAUCET_HOST="${FAUCET_HOST:-$(instance_internal_dns "${FAUCET_VM_NAME:-${PROVE_PROXY_VM_NAME:-gcp-prove-proxy}}")}"
ANVIL_VM_NAME="${ANVIL_VM_NAME:-${NODE_VM_NAME:-gcp-cp-ce}}"
ANVIL_HOST="${ANVIL_HOST:-$(instance_internal_dns "$ANVIL_VM_NAME")}"
POSTGRES_HOST="${POSTGRES_HOST:-$(instance_internal_dns "${POSTGRES_VM_NAME:-gcp-postgres}")}"
if [ "${L1_DEPLOYMENTS_NETWORK:-localhost}" != "localhost" ] || [ "${CHAIN_ID:-31337}" != "31337" ]; then
  DEFAULT_PUBLIC_L1_RPC_UPSTREAM="${ETH_RPC_URL:-}"
else
  DEFAULT_PUBLIC_L1_RPC_UPSTREAM="${ANVIL_HOST}:${ANVIL_PORT:-8545}"
fi

provision_vm "$NAME"

run_remote_script "$NAME" "$GCP_DIR/remote/update-caddy-entrypoints.sh" \
  "NOSTR_HOME=${NOSTR_HOME:-/opt/nostr-relay}" \
  "NOSTR_DOMAIN=${NOSTR_DOMAIN}" \
  "NOSTR_ALIAS_DOMAINS=${NOSTR_ALIAS_DOMAINS:-}" \
  "NOSTR_INTERNAL_PORT=${NOSTR_INTERNAL_PORT:-8080}" \
  "PUBLIC_COORDINATOR_DOMAIN=${PUBLIC_COORDINATOR_DOMAIN:-}" \
  "PUBLIC_COORDINATOR_ALIAS_DOMAINS=${PUBLIC_COORDINATOR_ALIAS_DOMAINS:-}" \
  "PUBLIC_COORDINATOR_UPSTREAM=${PUBLIC_COORDINATOR_UPSTREAM:-${NODE_HOST}:${COORDINATOR_EDGE_PORT:-1337}}" \
  "PUBLIC_REALM_DOMAIN=${PUBLIC_REALM_DOMAIN:-}" \
  "PUBLIC_REALM_ALIAS_DOMAINS=${PUBLIC_REALM_ALIAS_DOMAINS:-}" \
  "PUBLIC_REALM_UPSTREAM=${PUBLIC_REALM_UPSTREAM:-${NODE_HOST}:${REALM0_EDGE_PORT:-${REALM_EDGE_PORT:-1338}}}" \
  "PUBLIC_REALM1_DOMAIN=${PUBLIC_REALM1_DOMAIN:-}" \
  "PUBLIC_REALM1_ALIAS_DOMAINS=${PUBLIC_REALM1_ALIAS_DOMAINS:-}" \
  "PUBLIC_REALM1_UPSTREAM=${PUBLIC_REALM1_UPSTREAM:-${NODE_HOST}:${REALM1_EDGE_PORT:-1339}}" \
  "PUBLIC_PROVE_PROXY_DOMAIN=${PUBLIC_PROVE_PROXY_DOMAIN:-}" \
  "PUBLIC_PROVE_PROXY_ALIAS_DOMAINS=${PUBLIC_PROVE_PROXY_ALIAS_DOMAINS:-}" \
  "PUBLIC_PROVE_PROXY_UPSTREAM=${PUBLIC_PROVE_PROXY_UPSTREAM:-${PROVE_PROXY_HOST}:9999}" \
  "PUBLIC_FAUCET_DOMAIN=${PUBLIC_FAUCET_DOMAIN:-}" \
  "PUBLIC_FAUCET_ALIAS_DOMAINS=${PUBLIC_FAUCET_ALIAS_DOMAINS:-}" \
  "PUBLIC_FAUCET_UPSTREAM=${PUBLIC_FAUCET_UPSTREAM:-${FAUCET_HOST}:9998}" \
  "PUBLIC_L1_RPC_DOMAIN=${PUBLIC_L1_RPC_DOMAIN:-}" \
  "PUBLIC_L1_RPC_ALIAS_DOMAINS=${PUBLIC_L1_RPC_ALIAS_DOMAINS:-}" \
  "PUBLIC_L1_RPC_UPSTREAM=${PUBLIC_L1_RPC_UPSTREAM:-$DEFAULT_PUBLIC_L1_RPC_UPSTREAM}" \
  "PUBLIC_PSY_SERVICES_DOMAIN=${PUBLIC_PSY_SERVICES_DOMAIN:-}" \
  "PUBLIC_PSY_SERVICES_ALIAS_DOMAINS=${PUBLIC_PSY_SERVICES_ALIAS_DOMAINS:-}" \
  "PUBLIC_PSY_SERVICES_UPSTREAM=${PUBLIC_PSY_SERVICES_UPSTREAM:-${NODE_HOST}:${PSY_SERVICES_PORT:-3000}}" \
  "PUBLIC_INDEXER_DOMAIN=${PUBLIC_INDEXER_DOMAIN:-}" \
  "PUBLIC_INDEXER_ALIAS_DOMAINS=${PUBLIC_INDEXER_ALIAS_DOMAINS:-}" \
  "PUBLIC_INDEXER_UPSTREAM=${PUBLIC_INDEXER_UPSTREAM:-${POSTGRES_HOST}:${HASURA_EXTERNAL_PORT:-18080}}" \
  "PUBLIC_TRUST_SETUP_PATH=${PUBLIC_TRUST_SETUP_PATH:-/trust-setup}" \
  "PUBLIC_TRUST_SETUP_ROOT=${PUBLIC_TRUST_SETUP_ROOT:-${NOSTR_HOME:-/opt/nostr-relay}/public/trust-setup}"
