#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/lib/common.sh"

NAME="${NODE_VM_NAME:-parth-node-1}"
DEPLOY_INSTANCE="${DEPLOY_INSTANCE:-0}"
COORDINATOR_EDGE_PORT="${COORDINATOR_EDGE_PORT:-1337}"
UNIT="parth-coordinator-edge@${DEPLOY_INSTANCE}.service"

ensure_parth_vm "$NAME"

deploy_parth_service "$NAME" "coordinator-edge" "deploy-coordinator-edge" "$UNIT" \
  "DEPLOY_INSTANCE=$DEPLOY_INSTANCE" \
  "COORDINATOR_ID=${COORDINATOR_ID:-0}" \
  "COORDINATOR_SUB_ID=${COORDINATOR_SUB_ID:-0}" \
  "DB_NAMESPACE=${COORDINATOR_DB_NAMESPACE:-coordinator}" \
  "COORDINATOR_EDGE_PORT=$COORDINATOR_EDGE_PORT" \
  "LISTEN_ADDR=${LISTEN_ADDR:-0.0.0.0}"

run_health_check "$NAME" "jsonrpc" \
  "HEALTHCHECK_JSONRPC_URLS=${COORDINATOR_EDGE_HEALTHCHECK_JSONRPC_URL:-http://127.0.0.1:${COORDINATOR_EDGE_PORT}}" \
  "HEALTHCHECK_JSONRPC_METHOD=${PARTH_EDGE_HEALTHCHECK_METHOD:-psy_get_latest_checkpoint_id}" \
  "SYSTEMD_UNIT=$UNIT" \
  "HEALTHCHECK_START_DELAY=${COORDINATOR_EDGE_HEALTHCHECK_START_DELAY:-2}"
