use serde::{de::DeserializeOwned, Deserialize, Serialize};

use crate::common::core::{crypto::hash::{QHasher, ZeroableHash}, data::job_id::ProvingJobCircuitType, serializable::QPDSerializable};

pub trait QHashBase: PartialEq + ZeroableHash + Copy + Serialize + DeserializeOwned + QPDSerializable {}
pub trait QProofBase: PartialEq + Clone + Serialize + DeserializeOwned + QPDSerializable {}


#[derive(Clone, PartialEq, Eq, Debug, Serialize, Deserialize, Copy)]
#[serde(bound = "for<'de2> Hash: Deserialize<'de2>")]
pub struct QParthProofPublicInputsPreimage<Hash: QHashBase> {
    pub index: u64, // this index of the node in the merkle tree that this proof is proving updates to
    pub level: u8, // the level of the node in the merkle tree that this proof is proving updates to, 0 = root, tree_height = leaf
    pub old_node_value: Hash, // the old value of the node in the merkle tree that this proof proves an update to
    pub new_node_value: Hash, // the new value of the node in the merkle tree that this proof proves an update to
    pub rewards_hash_commitment: Hash, // hash(hash_two_to_one(left_child_reward_commitment, right_child_reward_commitment), new_reward_info_hash), for end cap proofs this is the zero hash
    pub checkpoint_tree_root: Hash, // hash of the checkpoint tree root that this operation is synced to, "the state of the block chain that this proof is aware of"
    pub total_guta_proofs_generated: u64, // total proofs generated by miners to get to this point, for end cap proofs this is 0, for guta proofs this is the sum of the two child proofs + 1
    pub total_user_updates: u64, // total user updates that have happened in the tree up to and including this proof, for end cap proofs this is 1, for guta proofs this is the sum of the two child proofs
    pub total_fees_paid: u64, // total fees paid by users in the tree up to and including this proof, for end cap proofs this is the fee paid by the user, for guta proofs this is the sum of the two child proofs
}

impl<Hash: QHashBase> QParthProofPublicInputsPreimage<Hash> {
    pub fn get_combined_preimage(left: &Self, right: &Self, new_rewards_hash_commitment: Hash, old_node_value: Hash, new_node_value: Hash, level: u8, index: u64, checkpoint_tree_root: Hash) -> Self {
        Self {
            index,
            level,
            old_node_value,
            new_node_value,
            rewards_hash_commitment: new_rewards_hash_commitment,
            checkpoint_tree_root,
            total_guta_proofs_generated: left.total_guta_proofs_generated + right.total_guta_proofs_generated + 1,
            total_user_updates: left.total_user_updates + right.total_user_updates,
            total_fees_paid: left.total_fees_paid + right.total_fees_paid,
        }
    }
}

pub trait QHasherBase<Hash: QHashBase, Proof: QProofBase>: QHasher<Hash> {
    fn get_proof_public_input(proof: &Proof) -> Hash; // the public inputs of the proof is a hash which is the hash of the QParthProofPublicInputsPreimage
    fn hash_proof_public_inputs_preimage(preimage: &QParthProofPublicInputsPreimage<Hash>) -> Hash;
}

pub trait QZKProofVerifier<Hash: QHashBase, Proof: QProofBase>: QHasherBase<Hash, Proof> {
    fn verify_zk_proof(&self, circuit_type: ProvingJobCircuitType, proof: &Proof) -> bool;
    fn verify_zk_proof_and_check_public_inputs(&self, circuit_type: ProvingJobCircuitType, proof: &Proof, public_inputs_preimage: &QParthProofPublicInputsPreimage<Hash>) -> bool {
        let public_inputs = Self::get_proof_public_input(proof);
        if public_inputs != Self::hash_proof_public_inputs_preimage(public_inputs_preimage) {
            return false;
        }
        self.verify_zk_proof(circuit_type, proof)
    }
}

pub trait QNetworkTypesConfigBase {
    type QHash: QHashBase;
    type ZKProof: QProofBase;
    type HasherBase: QHasherBase<Self::QHash, Self::ZKProof>;
    const GLOBAL_USER_TREE_HEIGHT: u8; // the height of the global user tree, ie. the full merkle tree that can hold all users
    const COORDINATOR_GLOBAL_USER_TREE_HEIGHT: u8; // the height of the global user tree stored in the coordinator (ie. the upper half of the merkle tree)
    const REALM_GLOBAL_USER_TREE_HEIGHT: u8; // the height of the global user tree stored in each realm (ie. the height of the sub-trees stored in each realm == GLOBAL_USER_TREE_HEIGHT - COORDINATOR_GLOBAL_USER_TREE_HEIGHT)
    const MAX_USERS: u64; // = 2**GLOBAL_USER_TREE_HEIGHT
    const MAX_REALMS: u32; // = 2**COORDINATOR_GLOBAL_USER_TREE_HEIGHT
    const MAX_USERS_PER_REALM: u32; // = 2**REALM_GLOBAL_USER_TREE_HEIGHT
}